// ============================================================
// SHAHNAMEH: RISE OF KINGS - GAME DATA v3
// ============================================================

// ---------------- HEROES (26 total) — balanced ----------------
const HEROES = [
  // ===== SSR - LEGENDARY =====
  {id:'rostam',ext:'png',name:{fa:'رستم دستان',en:'Rostam the Mighty'},title:{fa:'جهان‌پهلوان',en:'World Champion'},rarity:'SSR',class:'warrior',
    hp:320,atk:58,def:42,spd:12,crit:20,
    skill:{fa:'گرز گاوسر — ضربه ویرانگر ۲.۵ برابر',en:'Bull-Mace — 2.5× damage strike'},
    lore:{fa:'بزرگ‌ترین پهلوان شاهنامه، سوار بر رخش، هفت خوان را پیمود و دیو سپید را کشت.',en:'The greatest hero of Shahnameh; completed the Seven Labors.'},
    voice:'rostam_voice'},
  {id:'esfandiar',ext:'png',name:{fa:'اسفندیار رویین‌تن',en:'Esfandiar the Invincible'},title:{fa:'شاهزاده رویین‌تن',en:'Brazen Prince'},rarity:'SSR',class:'tank',
    hp:380,atk:44,def:58,spd:8,crit:10,
    skill:{fa:'تن رویین — ۳ نوبت مصونیت کامل',en:'Brazen Body — 3-turn immunity'},
    lore:{fa:'شاهزاده رویین‌تن که در هفت خوان اژدها و دیو را کشت.',en:'Invincible prince who slew dragons and demons in his seven trials.'},
    voice:'esfandiar_voice'},
  {id:'fereydun',ext:'png',name:{fa:'فریدون',en:'Fereydun the King'},title:{fa:'شاه دادگر',en:'The Just King'},rarity:'SSR',class:'support',
    hp:280,atk:40,def:38,spd:14,crit:15,
    skill:{fa:'فرمان شاهانه — درمان کل تیم +۳۰٪',en:'Royal Command — Heal team +30%'},
    lore:{fa:'ضحاک را شکست داد و در دماوند به بند کشید.',en:'The just king who chained Zahhak under Mt. Damavand.'},
    voice:'fereydun_voice'},
  {id:'jamshid',ext:'png',name:{fa:'جمشید',en:'Jamshid the Radiant'},title:{fa:'شاه فرمند',en:'The Radiant King'},rarity:'SSR',class:'mage',
    hp:240,atk:64,def:26,spd:13,crit:25,
    skill:{fa:'جام جهان‌نما — پیش‌گویی، آسیب دوبرابر',en:'Cup of Jamshid — Foresight, 2× damage'},
    lore:{fa:'مخترع آتش، فلز، پزشکی. جام جم را داشت.',en:'Inventor of fire, metal, medicine.'}},
  {id:'kourosh',ext:'png',name:{fa:'کوروش بزرگ',en:'Cyrus the Great'},title:{fa:'پدر ایران',en:'Father of Iran'},rarity:'SSR',class:'support',
    hp:290,atk:48,def:44,spd:15,crit:18,
    skill:{fa:'منشور کوروش — بونس دائم آمار تیم',en:'Cyrus Cylinder — Permanent team boost'},
    lore:{fa:'بنیانگذار هخامنشیان، نویسنده اولین منشور حقوق بشر.',en:'Founder of the Achaemenid Empire.'},
    voice:'kourosh_voice'},
  {id:'dariush',ext:'png',name:{fa:'داریوش بزرگ',en:'Darius the Great'},title:{fa:'شاهنشاه',en:'King of Kings'},rarity:'SSR',class:'warrior',
    hp:300,atk:52,def:40,spd:12,crit:16,
    skill:{fa:'راه شاهی — یک حمله اضافه برای همه',en:'Royal Road — All allies extra attack'},
    lore:{fa:'تخت‌جمشید را ساخت و راه شاهی را برپا کرد.',en:'Built Persepolis and the Royal Road.'},
    voice:'dariush_voice'},
  {id:'siavash',ext:'png',name:{fa:'سیاوش',en:'Siavash the Pure'},title:{fa:'شاهزاده پاک',en:'The Pure Prince'},rarity:'SSR',class:'mage',
    hp:220,atk:56,def:30,spd:16,crit:22,
    skill:{fa:'گذر از آتش — پاکسازی و درمان',en:'Pass Through Fire — Cleanse and heal'},
    lore:{fa:'برای اثبات بی‌گناهی از آتش گذشت.',en:'Walked through fire to prove his innocence.'},
    voice:'siavash_voice'},
  {id:'kaykhosrow',ext:'png',name:{fa:'کیخسرو',en:'Kay Khosrow'},title:{fa:'شاه مقدس',en:'The Holy King'},rarity:'SSR',class:'support',
    hp:270,atk:46,def:38,spd:14,crit:17,
    skill:{fa:'فره ایزدی — احیای متحد افتاده',en:'Divine Glory — Revive fallen ally'},
    lore:{fa:'پسر سیاوش که انتقام پدرش را گرفت.',en:'Son of Siavash who avenged his father.'}},
  {id:'garshasp',ext:'svg',name:{fa:'گرشاسپ',en:'Garshasp the Dragonslayer'},title:{fa:'اژدهاکش',en:'Dragon Slayer'},rarity:'SSR',class:'warrior',
    hp:310,atk:55,def:36,spd:11,crit:20,
    skill:{fa:'گرز اژدهاکش — سه ضربه پی‌درپی',en:'Dragon-Slayer Club — 3 strikes'},
    lore:{fa:'اژدهای گندرو را در ۹ روز کشت.',en:'Slew the great dragon Gandarva.'}},
  {id:'babak',ext:'svg',name:{fa:'بابک خرمدین',en:'Babak Khorramdin'},title:{fa:'قهرمان آزادی',en:'Champion of Freedom'},rarity:'SSR',class:'warrior',
    hp:280,atk:50,def:42,spd:15,crit:19,
    skill:{fa:'قیام سرخ — افزایش خشم متحدان',en:'Red Uprising — Rage boost for allies'},
    lore:{fa:'۲۰ سال از قلعه بذ در برابر عباسیان مقاومت کرد.',en:'Resisted the Abbasid Caliphate for 20 years.'}},
  {id:'surena',ext:'svg',name:{fa:'سورنا',en:'Surena the Parthian'},title:{fa:'فاتح روم',en:'Conqueror of Rome'},rarity:'SSR',class:'archer',
    hp:240,atk:62,def:32,spd:18,crit:25,
    skill:{fa:'رگبار پارتی — ۵ تیر پیاپی',en:'Parthian Shot — 5 arrows'},
    lore:{fa:'با ۱۰ هزار سرباز ۵۰ هزار رومی را در حران شکست داد.',en:'Defeated 50,000 Romans with 10,000 at Carrhae.'}},
  {id:'purandokht',ext:'svg',name:{fa:'پوران‌دخت',en:'Purandokht'},title:{fa:'ملکه ساسانی',en:'Sasanian Queen'},rarity:'SSR',class:'support',
    hp:250,atk:44,def:40,spd:15,crit:16,
    skill:{fa:'فرمان ملکه — سکوت دشمن',en:'Queens Decree — Silence enemy'},
    lore:{fa:'اولین ملکه ایران در دوره ساسانی.',en:'First queen of Iran in the Sasanian era.'},
    voice:'purandokht_voice'},

  // ===== SR - EPIC =====
  {id:'arash',ext:'png',name:{fa:'آرش کمانگیر',en:'Arash the Archer'},title:{fa:'مرزبان جاودان',en:'Eternal Borderer'},rarity:'SR',class:'archer',
    hp:150,atk:48,def:16,spd:20,crit:30,
    skill:{fa:'تیر جانفشان — آسیب ۳ برابر',en:'Soul-Arrow — Triple damage'},
    lore:{fa:'برای مرز ایران جان خود را در تیر نهاد.',en:'Put his soul into an arrow to define Irans border.'},
    voice:'arash_voice'},
  {id:'gordafarid',ext:'png',name:{fa:'گردآفرید',en:'Gordafarid'},title:{fa:'دخت پهلوان',en:'Warrior Maiden'},rarity:'SR',class:'warrior',
    hp:170,atk:38,def:26,spd:17,crit:22,
    skill:{fa:'شمشیر آذرین — ضدحمله ۱۰۰٪',en:'Fiery Sword — 100% counter'},
    lore:{fa:'نخستین بانوی جنگاور شاهنامه.',en:'First female warrior in Shahnameh.'},
    voice:'gordafarid_voice'},
  {id:'sohrab',ext:'png',name:{fa:'سهراب',en:'Sohrab'},title:{fa:'شیرزاده',en:'Lion Cub'},rarity:'SR',class:'warrior',
    hp:200,atk:42,def:24,spd:16,crit:20,
    skill:{fa:'خشم جوانی — سرعت دوبرابر ۳ نوبت',en:'Youthful Fury — 2× speed 3 turns'},
    lore:{fa:'پسر رستم که به دست پدر خود کشته شد.',en:'Son of Rostam, slain by his own father.'},
    voice:'sohrab_voice'},
  {id:'zal',ext:'png',name:{fa:'زال',en:'Zal the White'},title:{fa:'پرورده سیمرغ',en:'Raised by Simorgh'},rarity:'SR',class:'mage',
    hp:180,atk:40,def:30,spd:15,crit:18,
    skill:{fa:'پر سیمرغ — احضار سیمرغ',en:'Simorgh Feather — Summon Simorgh'},
    lore:{fa:'پدر رستم که سیمرغ او را پروراند.',en:'Father of Rostam, raised by Simorgh.'}},
  {id:'rudabeh',ext:'png',name:{fa:'رودابه',en:'Rudabeh'},title:{fa:'پرنسس کابل',en:'Princess of Kabul'},rarity:'SR',class:'support',
    hp:150,atk:34,def:22,spd:16,crit:15,
    skill:{fa:'گیسوی بلند — درمان متحد',en:'Long Tresses — Heal ally'},
    lore:{fa:'مادر رستم، عشق او و زال افسانه‌ای است.',en:'Mother of Rostam.'}},
  {id:'tahmineh',ext:'png',name:{fa:'تهمینه',en:'Tahmineh'},title:{fa:'مادر سهراب',en:'Mother of Sohrab'},rarity:'SR',class:'support',
    hp:145,atk:32,def:24,spd:17,crit:14,
    skill:{fa:'مهر مادری — احیای متحد',en:'Motherly Love — Revive ally'},
    lore:{fa:'شاهدخت سمنگان و مادر سهراب.',en:'Princess of Samangan.'}},
  {id:'bijan',ext:'png',name:{fa:'بیژن',en:'Bijan'},title:{fa:'پهلوان جوان',en:'Young Champion'},rarity:'SR',class:'warrior',
    hp:170,atk:38,def:26,spd:18,crit:19,
    skill:{fa:'شمشیر عاشق — آسیب بیشتر به قوی‌ترین',en:'Lovers Blade — Extra dmg to strongest'},
    lore:{fa:'عاشق منیژه دختر افراسیاب شد.',en:'Fell in love with Manijeh.'}},
  {id:'manijeh',ext:'svg',name:{fa:'منیژه',en:'Manijeh'},title:{fa:'دلداده بیژن',en:'Beloved of Bijan'},rarity:'SR',class:'support',
    hp:140,atk:30,def:22,spd:19,crit:13,
    skill:{fa:'وفاداری — کاهش آسیب متحدان',en:'Loyalty — Reduce ally dmg taken'},
    lore:{fa:'دختر افراسیاب که همه چیز را برای بیژن رها کرد.',en:'Daughter of Afrasiab.'}},
  {id:'sam',ext:'svg',name:{fa:'سام نریمان',en:'Sam Nariman'},title:{fa:'پهلوان کهن',en:'The Ancient Champion'},rarity:'SR',class:'tank',
    hp:240,atk:36,def:44,spd:9,crit:12,
    skill:{fa:'دیوار سام — جذب آسیب متحدان',en:'Sams Wall — Absorb ally damage'},
    lore:{fa:'پدر زال و پدربزرگ رستم.',en:'Father of Zal, grandfather of Rostam.'}},
  {id:'hooshang',ext:'svg',name:{fa:'هوشنگ',en:'Hooshang'},title:{fa:'کاشف آتش',en:'Discoverer of Fire'},rarity:'SR',class:'mage',
    hp:160,atk:46,def:22,spd:14,crit:20,
    skill:{fa:'آتش هوشنگ — سوزاندن مداوم',en:'Hooshangs Fire — Ongoing burn'},
    lore:{fa:'دومین شاه پیشدادی، کاشف آتش و جشن سده.',en:'Second Pishdadian king; discoverer of fire.'}},
  {id:'tahmoures',ext:'svg',name:{fa:'طهمورث دیوبند',en:'Tahmoures'},title:{fa:'به‌بند کشنده دیوان',en:'Demon Binder'},rarity:'SR',class:'warrior',
    hp:190,atk:42,def:34,spd:13,crit:17,
    skill:{fa:'زنجیر دیوبند — فلج دشمن ۲ نوبت',en:'Demon-Chain — Paralyze 2 turns'},
    lore:{fa:'سومین شاه پیشدادی که دیوان را به بند کشید.',en:'Third Pishdadian king; bound the demons.'}},
  {id:'bahram',ext:'svg',name:{fa:'بهرام گور',en:'Bahram Gur'},title:{fa:'شکارچی شاهی',en:'Royal Hunter'},rarity:'SR',class:'archer',
    hp:170,atk:44,def:24,spd:19,crit:24,
    skill:{fa:'تیر گورگیر — یک تیر، دو دشمن',en:'Onager Shot — One arrow, two enemies'},
    lore:{fa:'شاه ساسانی مشهور به شکار گورخر.',en:'Sasanian king famous for hunting.'}},
  {id:'shirin',ext:'svg',name:{fa:'شیرین',en:'Shirin'},title:{fa:'ملکه ارمنی',en:'Armenian Queen'},rarity:'SR',class:'support',
    hp:150,atk:34,def:26,spd:18,crit:16,
    skill:{fa:'عشق شیرین — افزایش کریتیکال متحدان',en:'Sweet Love — Boost ally crit'},
    lore:{fa:'همسر خسرو پرویز. عشق او و فرهاد افسانه‌ای است.',en:'Wife of Khosrow Parviz.'}},

  // ===== R - RARE =====
  {id:'kaveh',ext:'png',name:{fa:'کاوه آهنگر',en:'Kaveh the Blacksmith'},title:{fa:'قهرمان قیام',en:'Hero of Revolt'},rarity:'R',class:'warrior',
    hp:150,atk:28,def:24,spd:13,crit:15,
    skill:{fa:'درفش کاویانی — حمله متحدان +۳۰٪',en:'Kaviani Banner — Ally atk +30%'},
    lore:{fa:'آهنگری که مردم را علیه ضحاک شوراند.',en:'Blacksmith who led revolt against Zahhak.'},
    voice:'kaveh_voice'},
];

// ---------------- ENEMIES ----------------
const ENEMIES = [
  {id:'zahhak',ext:'png',name:{fa:'ضحاک ماردوش',en:'Zahhak the Serpent-King'},rarity:'SSR',hp:300,atk:34,def:22,spd:10,tier:1,voice:'zahhak_voice'},
  {id:'kondrow',ext:'svg',name:{fa:'کندرو',en:'Kondrow'},rarity:'R',hp:85,atk:15,def:10,spd:12,tier:1},
  {id:'kaftar_div',ext:'svg',name:{fa:'کفتار دیو',en:'Hyena Demon'},rarity:'N',hp:65,atk:13,def:6,spd:15,tier:1},
  {id:'sheer_div',ext:'svg',name:{fa:'شیر ژیان',en:'Fierce Lion'},rarity:'R',hp:130,atk:22,def:14,spd:14,tier:2},
  {id:'warg',ext:'svg',name:{fa:'گرگ سیاه',en:'Black Wolf'},rarity:'N',hp:75,atk:17,def:8,spd:18,tier:2},
  {id:'ghol',ext:'svg',name:{fa:'غول بیابانی',en:'Desert Giant'},rarity:'R',hp:170,atk:24,def:18,spd:8,tier:2},
  {id:'arjang_div',ext:'svg',name:{fa:'ارژنگ دیو',en:'Arjang Demon'},rarity:'SR',hp:200,atk:28,def:18,spd:11,tier:2},
  {id:'div_sepid',ext:'png',name:{fa:'دیو سپید',en:'The White Demon'},rarity:'SSR',hp:380,atk:40,def:28,spd:9,tier:2},
  {id:'kamus',ext:'svg',name:{fa:'کاموس کشانی',en:'Kamus of Kashan'},rarity:'SR',hp:220,atk:30,def:22,spd:12,tier:3},
  {id:'sohrab_boss',ext:'svg',name:{fa:'خاقان چین',en:'Khaqan of China'},rarity:'SR',hp:240,atk:32,def:24,spd:11,tier:3},
  {id:'barman',ext:'svg',name:{fa:'بارمان',en:'Barman'},rarity:'R',hp:160,atk:26,def:18,spd:14,tier:3},
  {id:'hooman',ext:'svg',name:{fa:'هومان تورانی',en:'Human of Turan'},rarity:'R',hp:180,atk:28,def:20,spd:13,tier:3},
  {id:'piran_visa',ext:'svg',name:{fa:'پیران ویسه',en:'Piran Visa'},rarity:'SR',hp:230,atk:32,def:26,spd:12,tier:4},
  {id:'garsivaz',ext:'svg',name:{fa:'گرسیوز',en:'Garsivaz'},rarity:'SR',hp:210,atk:34,def:22,spd:13,tier:4},
  {id:'shideh',ext:'svg',name:{fa:'شیده',en:'Shideh'},rarity:'SR',hp:220,atk:33,def:24,spd:12,tier:4},
  {id:'afrasiab',ext:'png',name:{fa:'افراسیاب',en:'Afrasiab King of Turan'},rarity:'SSR',hp:440,atk:44,def:32,spd:11,tier:4,voice:'afrasiab_voice'},
  {id:'sanjeh_div',ext:'svg',name:{fa:'سنجه دیو',en:'Sanjeh Demon'},rarity:'R',hp:190,atk:30,def:20,spd:12,tier:5},
  {id:'bakhtak',ext:'svg',name:{fa:'بختک',en:'Nightmare Spirit'},rarity:'R',hp:155,atk:34,def:14,spd:16,tier:5},
  {id:'shabrang_div',ext:'svg',name:{fa:'شبرنگ دیو',en:'Shabrang Demon'},rarity:'SR',hp:250,atk:38,def:24,spd:11,tier:5},
  {id:'narsi',ext:'svg',name:{fa:'نرسی دیو',en:'Narsi Demon'},rarity:'R',hp:200,atk:32,def:22,spd:13,tier:5},
  {id:'div_pashang',ext:'svg',name:{fa:'پشنگ دیو',en:'Pashang Demon'},rarity:'R',hp:210,atk:34,def:24,spd:12,tier:5},
  {id:'bulman',ext:'svg',name:{fa:'بولمان',en:'Bulman'},rarity:'N',hp:110,atk:22,def:14,spd:14,tier:5},
  {id:'akvan_div',ext:'png',name:{fa:'اکوان دیو',en:'Akvan the Wind Demon'},rarity:'SSR',hp:420,atk:46,def:34,spd:14,tier:6},
  {id:'azhdahak',ext:'png',name:{fa:'اژدهاک',en:'Azhi Dahaka'},rarity:'SSR',hp:500,atk:50,def:38,spd:10,tier:6},
];

// ---------------- ITEMS ----------------
const ITEMS = [
  {id:'sword_bronze',type:'weapon',rarity:'Common',name:{fa:'شمشیر برنزی',en:'Bronze Sword'},atk:5},
  {id:'sword_iron',type:'weapon',rarity:'Common',name:{fa:'شمشیر آهنی',en:'Iron Sword'},atk:10},
  {id:'sword_steel',type:'weapon',rarity:'Rare',name:{fa:'شمشیر فولادین',en:'Steel Sword'},atk:20},
  {id:'sword_shahi',type:'weapon',rarity:'Epic',name:{fa:'شمشیر شاهی',en:'Royal Sword'},atk:35},
  {id:'shamshir_shahi',type:'weapon',rarity:'Legendary',name:{fa:'شمشیر افسانه‌ای',en:'Legendary Blade'},atk:60,crit:10},
  {id:'gorz_gavsar',type:'weapon',rarity:'Legendary',name:{fa:'گرز گاوسر',en:'Bull-Headed Mace'},atk:75,crit:5,hero:'rostam'},
  {id:'kaman_arash',type:'weapon',rarity:'Legendary',name:{fa:'کمان آرش',en:'Bow of Arash'},atk:70,crit:15,hero:'arash'},
  {id:'nezeh_pahlavi',type:'weapon',rarity:'Epic',name:{fa:'نیزه پهلوی',en:'Pahlavi Spear'},atk:40,spd:5},
  {id:'helm_leather',type:'helm',rarity:'Common',name:{fa:'کلاه چرمی',en:'Leather Cap'},def:3,hp:10},
  {id:'helm_bronze',type:'helm',rarity:'Common',name:{fa:'خود برنزی',en:'Bronze Helm'},def:6,hp:20},
  {id:'helm_shahi',type:'helm',rarity:'Epic',name:{fa:'تاج شاهی',en:'Royal Crown'},def:15,hp:60,atk:5},
  {id:'taj_kiani',type:'helm',rarity:'Legendary',name:{fa:'تاج کیانی',en:'Kiani Crown'},def:25,hp:100,atk:15},
  {id:'armor_leather',type:'armor',rarity:'Common',name:{fa:'زره چرمی',en:'Leather Armor'},def:10,hp:30},
  {id:'armor_scale',type:'armor',rarity:'Rare',name:{fa:'زره پولکی',en:'Scale Mail'},def:20,hp:60},
  {id:'babr_bayan',type:'armor',rarity:'Legendary',name:{fa:'ببر بیان',en:'Tiger-Cloak Armor'},def:45,hp:150,atk:10,hero:'rostam'},
  {id:'armor_javidan',type:'armor',rarity:'Epic',name:{fa:'زره جاویدان',en:'Immortals Armor'},def:32,hp:100},
  {id:'boots_leather',type:'boots',rarity:'Common',name:{fa:'چکمه چرمی',en:'Leather Boots'},def:3,spd:2},
  {id:'boots_shahi',type:'boots',rarity:'Rare',name:{fa:'چکمه شاهی',en:'Royal Boots'},def:8,spd:5},
  {id:'boots_rakhsh',type:'boots',rarity:'Legendary',name:{fa:'نعل رخش',en:'Rakhsh Horseshoes'},def:15,spd:12,hp:50},
  {id:'ring_bronze',type:'ring',rarity:'Common',name:{fa:'انگشتر برنزی',en:'Bronze Ring'},atk:3},
  {id:'ring_firooz',type:'ring',rarity:'Rare',name:{fa:'انگشتر فیروزه',en:'Turquoise Ring'},atk:10,crit:5},
  {id:'ring_yaghout',type:'ring',rarity:'Epic',name:{fa:'انگشتر یاقوت',en:'Ruby Ring'},atk:18,crit:8},
  {id:'mohreh_simorgh',type:'ring',rarity:'Legendary',name:{fa:'مهره سیمرغ',en:'Simorgh Amulet'},atk:25,def:15,hp:80,crit:12},
];

// ---------------- PETS ----------------
const PETS = [
  {id:'simorgh',name:{fa:'سیمرغ',en:'Simorgh'},rarity:'SSR',
    bonus:{fa:'+۲۰٪ HP، +۱۰٪ CRIT به کل تیم',en:'+20% HP, +10% CRIT to team'},
    stats:{hp:0.20, crit:0.10},
    lore:{fa:'مرغ افسانه‌ای که زال را پروراند.',en:'Legendary bird that raised Zal.'}},
  {id:'rakhsh',name:{fa:'رخش',en:'Rakhsh'},rarity:'SR',
    bonus:{fa:'+۱۵٪ سرعت، +۱۰٪ حمله',en:'+15% Speed, +10% Attack'},
    stats:{spd:0.15, atk:0.10},
    lore:{fa:'اسب افسانه‌ای رستم.',en:'Legendary warhorse of Rostam.'}},
  {id:'homa',name:{fa:'هما',en:'Homa'},rarity:'SR',
    bonus:{fa:'+۱۵٪ دفاع، +۵٪ درمان در هر نوبت',en:'+15% DEF, +5% heal per turn'},
    stats:{def:0.15, regen:0.05},
    lore:{fa:'مرغ شاهی که سایه‌اش تاج می‌بخشد.',en:'Royal bird whose shadow grants kingship.'}},
];

// ---------------- BUILDINGS ----------------
const BUILDINGS = [
  {id:'palace',name:{fa:'کاخ آپادانا',en:'Apadana Palace'},desc:{fa:'افزایش سقف تیم',en:'Team cap'},base:200,icon:'🏛'},
  {id:'fire_temple',name:{fa:'آتشکده',en:'Fire Temple'},desc:{fa:'درآمد طلا در ساعت',en:'Gold per hour'},base:150,icon:'🔥'},
  {id:'bazaar',name:{fa:'بازار پارس',en:'Persian Bazaar'},desc:{fa:'کاهش هزینه ارتقا',en:'Reduce upgrade cost'},base:180,icon:'🏺'},
  {id:'immortals',name:{fa:'پادگان جاویدان',en:'Immortals Barracks'},desc:{fa:'قدرت پهلوانان',en:'Hero power'},base:300,icon:'⚔'},
  {id:'library',name:{fa:'کتابخانه اوستا',en:'Avesta Library'},desc:{fa:'کریتیکال ریت',en:'Critical rate'},base:400,icon:'📜'},
  {id:'stable',name:{fa:'اصطبل رخش',en:'Rakhsh Stables'},desc:{fa:'سرعت پهلوانان',en:'Hero speed'},base:250,icon:'🐎'},
];

// ---------------- STORY CAMPAIGN (7 Chapters) ----------------
const CHAPTERS = [
  {id:1,title:{fa:'قیام کاوه',en:'Kavehs Uprising'},scene:'fire',
    intro:{fa:['به نام خداوند جان و خرد، کزین برتر اندیشه برنگذرد.',
      'هزاران سال پیش، ضحاک ماردوش با فریب اهریمن، جمشید شاه را کشت و بر تخت پارس نشست.',
      'دو مار سیاه از دوش‌هایش رویید که هر روز خوراکشان مغز جوانان ایرانی بود.',
      'مردم در وحشت زندگی می‌کردند، تا اینکه کاوه، آهنگر ساده، شانزده پسر خود را از دست داد.',
      'او پیش‌بند چرمی خود را بر سر نیزه کرد و درفش کاویانی را برافراشت.',
      'ای پهلوان! به این قیام بپیوند و ضحاک را از تخت به زیر کش!'],
      en:['In the name of the Lord of soul and wisdom.',
      'Thousands of years ago, Zahhak the Serpent-King murdered Jamshid and took the throne of Persia.',
      'Two black serpents grew from his shoulders, feeding daily on the brains of young Iranians.',
      'The people lived in terror, until Kaveh the blacksmith lost sixteen of his sons.',
      'He raised his leather apron on a spear — the Kaviani Banner was born.',
      'Hero! Join this uprising and cast Zahhak from his throne!']},
    stages:[
      {enemy:'kaftar_div',reward:{gold:50,exp:20}},
      {enemy:'kondrow',reward:{gold:80,exp:30}},
      {enemy:'warg',reward:{gold:100,exp:40}},
      {enemy:'kaftar_div',reward:{gold:120,exp:50},wave:2},
      {enemy:'zahhak',boss:true,reward:{gold:500,gems:50,exp:200,item:'sword_iron'}}],
    outro:{fa:['ضحاک شکست خورد! فریدون او را به بند کشید و در غار دماوند زندانی کرد.','ایران رها شد. یک شمشیر آهنی پاداش توست!'],
      en:['Zahhak is defeated! Fereydun chained him inside Mount Damavand.','Iran is free. An Iron Sword is your reward!']}},
  {id:2,title:{fa:'هفت خوان رستم',en:'Seven Labors of Rostam'},scene:'mountain',
    intro:{fa:['کیکاووس شاه در مازندران به دست دیو سپید اسیر شد.','رستم دستان، جهان‌پهلوان ایران، برای نجات شاه به راه افتاد.','هفت خوان در برابر اوست: شیر ژیان، تشنگی، اژدها، جادوگر، اولاد، ارژنگ، و دیو سپید.','رخش پیر، اما وفادار، در کنار اوست. آماده باش!'],
      en:['King Kay Kavus was captured by the White Demon in Mazandaran.','Rostam the World-Champion set out to rescue him.','Seven Labors await: the Lion, deadly Thirst, the Dragon, the Sorceress, Aulad, Arjang, and the White Demon.','Old but loyal Rakhsh rides with him.']},
    stages:[
      {enemy:'sheer_div',reward:{gold:100,exp:60}},
      {enemy:'warg',wave:3,reward:{gold:120,exp:80}},
      {enemy:'ghol',reward:{gold:150,exp:100}},
      {enemy:'sheer_div',wave:2,reward:{gold:180,exp:120}},
      {enemy:'arjang_div',boss:true,reward:{gold:400,gems:30,exp:200,item:'helm_bronze'}},
      {enemy:'ghol',wave:2,reward:{gold:220,exp:150}},
      {enemy:'div_sepid',boss:true,reward:{gold:1000,gems:100,exp:500,item:'babr_bayan'}}],
    outro:{fa:['رستم دیو سپید را کشت و جگرش را برای درمان کوری کیکاووس آورد.','ببر بیان — زره افسانه‌ای رستم — پاداش توست!'],
      en:['Rostam slew the White Demon and used his liver to cure King Kay Kavus.','The Tiger-Cloak is your reward!']}},
  {id:3,title:{fa:'رستم و سهراب',en:'Rostam and Sohrab'},scene:'battle',
    intro:{fa:['سهراب، پسر رستم، بزرگ شده و پهلوانی چیره‌دست است. اما پدرش را نمی‌شناسد.','با سپاه توران به ایران می‌تازد. گردآفرید در برابرش می‌ایستد.','سرنوشتی تراژیک در انتظار است!'],
      en:['Sohrab, son of Rostam, has grown mighty. But he knows not his father.','He marches on Iran. Gordafarid stands against him.','A tragic fate awaits!']},
    stages:[
      {enemy:'barman',reward:{gold:150,exp:100}},
      {enemy:'hooman',reward:{gold:180,exp:120}},
      {enemy:'barman',wave:2,reward:{gold:200,exp:140}},
      {enemy:'kamus',boss:true,reward:{gold:500,gems:40,exp:250,item:'sword_steel'}},
      {enemy:'hooman',wave:3,reward:{gold:250,exp:180}},
      {enemy:'sohrab_boss',boss:true,reward:{gold:1200,gems:120,exp:600,item:'nezeh_pahlavi'}}],
    outro:{fa:['رستم پس از کشتن سهراب، نوشدارو خواست، اما دیر رسید.','گریست چون ابر بهار. این داغ برای همیشه در دل او ماند.'],
      en:['After slaying Sohrab, Rostam asked for the elixir — but too late.','He wept like a spring cloud.']}},
  {id:4,title:{fa:'انتقام سیاوش',en:'Vengeance for Siavash'},scene:'palace',
    intro:{fa:['سیاوش شاهزاده پاک به دست افراسیاب کشته شد.','کیخسرو، پسر سیاوش، اکنون شاه ایران است. زمان انتقام فرا رسیده.','رستم، گودرز، توس و دیگر پهلوانان به توران می‌تازند!'],
      en:['The pure prince Siavash was slain by Afrasiab.','Kay Khosrow is now king. The time for vengeance has come.','Rostam and other heroes march on Turan!']},
    stages:[
      {enemy:'piran_visa',reward:{gold:250,exp:200}},
      {enemy:'garsivaz',reward:{gold:280,exp:220}},
      {enemy:'shideh',reward:{gold:300,exp:250}},
      {enemy:'piran_visa',wave:2,reward:{gold:350,exp:280}},
      {enemy:'afrasiab',boss:true,reward:{gold:2000,gems:200,exp:1000,item:'armor_javidan'}}],
    outro:{fa:['افراسیاب کشته شد و خون سیاوش پاک شد.','کیخسرو پس از پیروزی، سلطنت را رها کرد و در کوهی ناپدید شد.'],
      en:['Afrasiab is slain, Siavashs blood is avenged.','Kay Khosrow abandoned the throne and vanished.']}},
  {id:5,title:{fa:'بیژن و منیژه',en:'Bijan and Manijeh'},scene:'night',
    intro:{fa:['بیژن در باغ منیژه — دختر افراسیاب — گیر افتاد.','افراسیاب او را در چاهی عمیق افکند. تنها رستم می‌تواند نجاتش دهد!'],
      en:['Bijan was caught in Manijehs garden.','Afrasiab threw him into a deep pit. Only Rostam can save him!']},
    stages:[
      {enemy:'sanjeh_div',reward:{gold:300,exp:250}},
      {enemy:'bakhtak',reward:{gold:320,exp:270}},
      {enemy:'narsi',reward:{gold:350,exp:300}},
      {enemy:'div_pashang',wave:2,reward:{gold:400,exp:350}},
      {enemy:'shabrang_div',boss:true,reward:{gold:1500,gems:150,exp:800,item:'ring_yaghout'}}],
    outro:{fa:['بیژن از چاه رها شد. منیژه با او به ایران آمد.','انگشتر یاقوت پاداش توست!'],
      en:['Bijan was freed. The Ruby Ring is your reward!']}},
  {id:6,title:{fa:'اکوان دیو',en:'The Wind Demon'},scene:'cave',
    intro:{fa:['اکوان دیو، دیو باد، در دشت‌های ایران گله‌های شاه را می‌درید.','رستم به شکار او رفت.'],
      en:['Akvan the Wind Demon devoured the kings herds.','Rostam went to hunt him.']},
    stages:[
      {enemy:'bulman',wave:3,reward:{gold:400,exp:400}},
      {enemy:'shabrang_div',wave:2,reward:{gold:500,exp:500}},
      {enemy:'div_pashang',wave:3,reward:{gold:600,exp:600}},
      {enemy:'akvan_div',boss:true,reward:{gold:2500,gems:250,exp:1500,item:'boots_rakhsh'}}],
    outro:{fa:['اکوان دیو با گرز رستم کشته شد. نعل رخش پاداش توست!'],
      en:['Akvan Demon fell to Rostams mace.']}},
  {id:7,title:{fa:'اژدهاک',en:'Azhi Dahaka'},scene:'desert',
    intro:{fa:['ضحاک از بندهای دماوند رها می‌شود و به شکل اژدهاک اهریمنی سر برمی‌آورد.','این آخرین نبرد است!'],
      en:['Zahhak breaks free from Damavand as Azhi Dahaka.','This is the final battle!']},
    stages:[
      {enemy:'shabrang_div',wave:3,reward:{gold:600,exp:700}},
      {enemy:'akvan_div',wave:2,reward:{gold:800,exp:900}},
      {enemy:'afrasiab',wave:2,reward:{gold:1000,exp:1100}},
      {enemy:'azhdahak',boss:true,reward:{gold:5000,gems:500,exp:3000,item:'mohreh_simorgh'}}],
    outro:{fa:['اژدهاک شکست خورد! نور بر تاریکی چیره شد. ایران‌زمین جاودان است.','مهره سیمرغ از آن توست. حال به مرحله بی‌نهایت وارد شو!'],
      en:['Azhi Dahaka defeated! Light triumphs. Iran endures forever.']}},
];

// ---------------- QUESTS (Daily/Weekly/Achievement — 50+) ----------------
const QUESTS = [
  // Daily
  {id:'d_battle3',type:'daily',name:{fa:'۳ نبرد در روز',en:'3 battles today'},goal:3,stat:'battles',reward:{gold:100,exp:50}},
  {id:'d_battle10',type:'daily',name:{fa:'۱۰ نبرد در روز',en:'10 battles today'},goal:10,stat:'battles',reward:{gold:300,gems:5}},
  {id:'d_win5',type:'daily',name:{fa:'۵ پیروزی',en:'Win 5 battles'},goal:5,stat:'wins',reward:{gold:200,scrolls:1}},
  {id:'d_summon1',type:'daily',name:{fa:'یک احضار انجام بده',en:'Perform 1 summon'},goal:1,stat:'summons',reward:{gems:20}},
  {id:'d_upgrade',type:'daily',name:{fa:'یک قهرمان ارتقا بده',en:'Upgrade a hero'},goal:1,stat:'upgrades',reward:{gold:200}},
  {id:'d_idle',type:'daily',name:{fa:'پاداش آفلاین دریافت کن',en:'Claim idle rewards'},goal:1,stat:'idleClaims',reward:{gold:150}},
  {id:'d_build',type:'daily',name:{fa:'یک بنا ارتقا بده',en:'Upgrade a building'},goal:1,stat:'builds',reward:{gold:250}},
  {id:'d_equip',type:'daily',name:{fa:'یک آیتم تجهیز کن',en:'Equip an item'},goal:1,stat:'equips',reward:{gold:100}},
  {id:'d_endless',type:'daily',name:{fa:'حالت بی‌نهایت را بازی کن',en:'Play endless mode'},goal:1,stat:'endless',reward:{gems:15}},
  {id:'d_minigame',type:'daily',name:{fa:'یک مینی‌گیم بازی کن',en:'Play a minigame'},goal:1,stat:'minigames',reward:{gold:200,gems:5}},
  // Weekly
  {id:'w_battle50',type:'weekly',name:{fa:'۵۰ نبرد در هفته',en:'50 battles/week'},goal:50,stat:'battles',reward:{gold:2000,gems:50}},
  {id:'w_wins25',type:'weekly',name:{fa:'۲۵ پیروزی',en:'25 wins'},goal:25,stat:'wins',reward:{gold:1500,scrolls:5}},
  {id:'w_summon10',type:'weekly',name:{fa:'۱۰ احضار',en:'10 summons'},goal:10,stat:'summons',reward:{gems:100}},
  {id:'w_lvl50',type:'weekly',name:{fa:'یک قهرمان به لول ۵۰ برسان',en:'Reach a hero to Lv.50'},goal:50,stat:'maxLevel',reward:{gold:5000,gems:100}},
  {id:'w_stage20',type:'weekly',name:{fa:'به مرحله ۲۰ برس',en:'Reach stage 20'},goal:20,stat:'endlessMax',reward:{gems:150,item:'sword_steel'}},
  // Story quests
  {id:'q_ch1',type:'story',name:{fa:'فصل ۱ را تمام کن',en:'Complete Chapter 1'},goal:1,stat:'ch1',reward:{gems:50,scrolls:3}},
  {id:'q_ch2',type:'story',name:{fa:'فصل ۲ را تمام کن',en:'Complete Chapter 2'},goal:1,stat:'ch2',reward:{gems:80,scrolls:5}},
  {id:'q_ch3',type:'story',name:{fa:'فصل ۳ را تمام کن',en:'Complete Chapter 3'},goal:1,stat:'ch3',reward:{gems:100,item:'ring_firooz'}},
  {id:'q_ch4',type:'story',name:{fa:'فصل ۴ را تمام کن',en:'Complete Chapter 4'},goal:1,stat:'ch4',reward:{gems:150,item:'helm_shahi'}},
  {id:'q_ch5',type:'story',name:{fa:'فصل ۵ را تمام کن',en:'Complete Chapter 5'},goal:1,stat:'ch5',reward:{gems:200}},
  {id:'q_ch6',type:'story',name:{fa:'فصل ۶ را تمام کن',en:'Complete Chapter 6'},goal:1,stat:'ch6',reward:{gems:250,item:'armor_javidan'}},
  {id:'q_ch7',type:'story',name:{fa:'فصل ۷ را تمام کن',en:'Complete Chapter 7'},goal:1,stat:'ch7',reward:{gems:500,item:'taj_kiani'}},
];

// ---------------- ACHIEVEMENTS (100+) ----------------
const ACHIEVEMENTS = [
  // First blood
  {id:'a_firstwin',cat:'battle',name:{fa:'اولین پیروزی',en:'First Blood'},desc:{fa:'در یک نبرد پیروز شو',en:'Win your first battle'},goal:1,stat:'wins',reward:{gold:100,gems:10}},
  {id:'a_win10',cat:'battle',name:{fa:'ده پیروزی',en:'Decade of Wins'},desc:{fa:'۱۰ نبرد را ببر',en:'Win 10 battles'},goal:10,stat:'wins',reward:{gold:300,gems:20}},
  {id:'a_win50',cat:'battle',name:{fa:'نیم‌قرن پیروزی',en:'Half-Century'},desc:{fa:'۵۰ نبرد را ببر',en:'Win 50 battles'},goal:50,stat:'wins',reward:{gold:1500,gems:50}},
  {id:'a_win100',cat:'battle',name:{fa:'صد پیروزی',en:'Century'},desc:{fa:'۱۰۰ نبرد را ببر',en:'Win 100 battles'},goal:100,stat:'wins',reward:{gold:3000,gems:100,item:'sword_steel'}},
  {id:'a_win500',cat:'battle',name:{fa:'پنج‌صد پیروزی',en:'Warlord'},desc:{fa:'۵۰۰ نبرد را ببر',en:'Win 500 battles'},goal:500,stat:'wins',reward:{gems:500,item:'shamshir_shahi'}},
  {id:'a_win1000',cat:'battle',name:{fa:'هزار پیروزی',en:'Legend'},desc:{fa:'۱۰۰۰ نبرد را ببر',en:'Win 1000 battles'},goal:1000,stat:'wins',reward:{gems:1000,item:'mohreh_simorgh'}},
  {id:'a_lose1',cat:'battle',name:{fa:'اولین شکست',en:'First Fall'},desc:{fa:'یک شکست را تجربه کن',en:'Experience defeat'},goal:1,stat:'losses',reward:{gems:20}},
  {id:'a_boss1',cat:'battle',name:{fa:'اولین باس',en:'Boss Slayer'},desc:{fa:'یک باس را شکست بده',en:'Defeat a boss'},goal:1,stat:'bosses',reward:{gems:30}},
  {id:'a_boss5',cat:'battle',name:{fa:'پنج باس',en:'Boss Hunter'},desc:{fa:'۵ باس را شکست بده',en:'Defeat 5 bosses'},goal:5,stat:'bosses',reward:{gems:100,item:'ring_yaghout'}},
  {id:'a_crit100',cat:'battle',name:{fa:'صد ضربه کریتیکال',en:'Crit Master'},desc:{fa:'۱۰۰ ضربه کریتیکال بزن',en:'Land 100 crits'},goal:100,stat:'crits',reward:{gold:1000}},
  {id:'a_crit1000',cat:'battle',name:{fa:'هزار کریتیکال',en:'Crit Legend'},desc:{fa:'۱۰۰۰ ضربه کریتیکال',en:'Land 1000 crits'},goal:1000,stat:'crits',reward:{gems:200,item:'ring_yaghout'}},
  // Heroes
  {id:'a_hero3',cat:'hero',name:{fa:'سه پهلوان',en:'Team of Three'},desc:{fa:'۳ پهلوان جمع کن',en:'Collect 3 heroes'},goal:3,stat:'heroCount',reward:{gold:200}},
  {id:'a_hero10',cat:'hero',name:{fa:'ده پهلوان',en:'Growing Army'},desc:{fa:'۱۰ پهلوان جمع کن',en:'Collect 10 heroes'},goal:10,stat:'heroCount',reward:{gems:50}},
  {id:'a_hero20',cat:'hero',name:{fa:'بیست پهلوان',en:'Legions'},desc:{fa:'۲۰ پهلوان جمع کن',en:'Collect 20 heroes'},goal:20,stat:'heroCount',reward:{gems:200,scrolls:5}},
  {id:'a_heroAll',cat:'hero',name:{fa:'تمام پهلوانان',en:'Full Roster'},desc:{fa:'همه ۲۶ پهلوان را جمع کن',en:'Collect all 26 heroes'},goal:26,stat:'heroCount',reward:{gems:1000,item:'mohreh_simorgh'}},
  {id:'a_ssr1',cat:'hero',name:{fa:'اولین SSR',en:'First Legendary'},desc:{fa:'یک قهرمان SSR بگیر',en:'Get a Legendary hero'},goal:1,stat:'ssrCount',reward:{gems:100}},
  {id:'a_ssr5',cat:'hero',name:{fa:'پنج SSR',en:'Legendary Collector'},desc:{fa:'۵ قهرمان SSR بگیر',en:'Get 5 Legendaries'},goal:5,stat:'ssrCount',reward:{gems:300,scrolls:10}},
  {id:'a_lvl10',cat:'hero',name:{fa:'لول ۱۰',en:'Level 10'},desc:{fa:'یک قهرمان به لول ۱۰',en:'Hero to Lv.10'},goal:10,stat:'maxLevel',reward:{gold:500}},
  {id:'a_lvl25',cat:'hero',name:{fa:'لول ۲۵',en:'Level 25'},desc:{fa:'یک قهرمان به لول ۲۵',en:'Hero to Lv.25'},goal:25,stat:'maxLevel',reward:{gems:100}},
  {id:'a_lvl50',cat:'hero',name:{fa:'لول ۵۰',en:'Level 50'},desc:{fa:'یک قهرمان به لول ۵۰',en:'Hero to Lv.50'},goal:50,stat:'maxLevel',reward:{gems:250,item:'armor_javidan'}},
  {id:'a_lvl100',cat:'hero',name:{fa:'لول ۱۰۰',en:'Master'},desc:{fa:'یک قهرمان به لول ۱۰۰',en:'Hero to Lv.100'},goal:100,stat:'maxLevel',reward:{gems:1000,item:'taj_kiani'}},
  // Story
  {id:'a_ch1',cat:'story',name:{fa:'فصل ۱ کامل',en:'Chapter 1 Done'},desc:{fa:'فصل قیام کاوه را تمام کن',en:'Complete Kavehs chapter'},goal:1,stat:'ch1',reward:{gems:50}},
  {id:'a_ch2',cat:'story',name:{fa:'فصل ۲ کامل',en:'Chapter 2 Done'},desc:{fa:'هفت خوان را تمام کن',en:'Complete Seven Labors'},goal:1,stat:'ch2',reward:{gems:80,item:'helm_bronze'}},
  {id:'a_ch3',cat:'story',name:{fa:'فصل ۳ کامل',en:'Chapter 3 Done'},desc:{fa:'رستم و سهراب',en:'Rostam & Sohrab done'},goal:1,stat:'ch3',reward:{gems:100}},
  {id:'a_ch4',cat:'story',name:{fa:'فصل ۴ کامل',en:'Chapter 4 Done'},desc:{fa:'انتقام سیاوش',en:'Siavash avenged'},goal:1,stat:'ch4',reward:{gems:150}},
  {id:'a_ch5',cat:'story',name:{fa:'فصل ۵ کامل',en:'Chapter 5 Done'},desc:{fa:'بیژن و منیژه',en:'Bijan freed'},goal:1,stat:'ch5',reward:{gems:200}},
  {id:'a_ch6',cat:'story',name:{fa:'فصل ۶ کامل',en:'Chapter 6 Done'},desc:{fa:'اکوان دیو',en:'Akvan slain'},goal:1,stat:'ch6',reward:{gems:250}},
  {id:'a_ch7',cat:'story',name:{fa:'همه فصل‌ها',en:'All Chapters'},desc:{fa:'همه ۷ فصل را تمام کن',en:'Complete all 7 chapters'},goal:1,stat:'ch7',reward:{gems:1000,item:'taj_kiani'}},
  {id:'a_endless10',cat:'story',name:{fa:'بی‌نهایت ۱۰',en:'Endless 10'},desc:{fa:'به مرحله ۱۰ بی‌نهایت برس',en:'Reach endless stage 10'},goal:10,stat:'endlessMax',reward:{gems:100}},
  {id:'a_endless50',cat:'story',name:{fa:'بی‌نهایت ۵۰',en:'Endless 50'},desc:{fa:'به مرحله ۵۰ بی‌نهایت',en:'Reach endless stage 50'},goal:50,stat:'endlessMax',reward:{gems:500,item:'ring_yaghout'}},
  {id:'a_endless100',cat:'story',name:{fa:'بی‌نهایت ۱۰۰',en:'Endless 100'},desc:{fa:'به مرحله ۱۰۰ بی‌نهایت',en:'Reach endless stage 100'},goal:100,stat:'endlessMax',reward:{gems:2000,item:'mohreh_simorgh'}},
  // Wealth
  {id:'a_gold10k',cat:'wealth',name:{fa:'ده هزار طلا',en:'10K Gold'},desc:{fa:'۱۰,۰۰۰ طلا داشته باش',en:'Own 10K gold'},goal:10000,stat:'goldMax',reward:{gems:50}},
  {id:'a_gold100k',cat:'wealth',name:{fa:'صد هزار طلا',en:'100K Gold'},desc:{fa:'۱۰۰,۰۰۰ طلا داشته باش',en:'Own 100K gold'},goal:100000,stat:'goldMax',reward:{gems:200}},
  {id:'a_gold1M',cat:'wealth',name:{fa:'میلیونر',en:'Millionaire'},desc:{fa:'۱,۰۰۰,۰۰۰ طلا داشته باش',en:'Own 1M gold'},goal:1000000,stat:'goldMax',reward:{gems:1000}},
  {id:'a_gems100',cat:'wealth',name:{fa:'۱۰۰ الماس',en:'100 Gems'},desc:{fa:'۱۰۰ الماس داشته باش',en:'Own 100 gems'},goal:100,stat:'gemsMax',reward:{gold:500}},
  {id:'a_gems1000',cat:'wealth',name:{fa:'۱۰۰۰ الماس',en:'1K Gems'},desc:{fa:'۱۰۰۰ الماس داشته باش',en:'Own 1000 gems'},goal:1000,stat:'gemsMax',reward:{scrolls:10}},
  // Summons
  {id:'a_sum5',cat:'summon',name:{fa:'۵ احضار',en:'5 Summons'},desc:{fa:'۵ احضار انجام بده',en:'Perform 5 summons'},goal:5,stat:'summons',reward:{gems:30}},
  {id:'a_sum25',cat:'summon',name:{fa:'۲۵ احضار',en:'25 Summons'},desc:{fa:'۲۵ احضار انجام بده',en:'Perform 25 summons'},goal:25,stat:'summons',reward:{gems:100}},
  {id:'a_sum100',cat:'summon',name:{fa:'۱۰۰ احضار',en:'100 Summons'},desc:{fa:'۱۰۰ احضار انجام بده',en:'Perform 100 summons'},goal:100,stat:'summons',reward:{gems:500,scrolls:20}},
  // Buildings
  {id:'a_build5',cat:'build',name:{fa:'۵ ارتقای بنا',en:'5 Upgrades'},desc:{fa:'۵ بار بنا ارتقا بده',en:'Upgrade buildings 5 times'},goal:5,stat:'builds',reward:{gold:500}},
  {id:'a_build25',cat:'build',name:{fa:'۲۵ ارتقای بنا',en:'25 Upgrades'},desc:{fa:'۲۵ بار ارتقا بده',en:'Upgrade buildings 25 times'},goal:25,stat:'builds',reward:{gems:150}},
  {id:'a_bldMax',cat:'build',name:{fa:'بنای لول ۱۰',en:'Building Lv.10'},desc:{fa:'یک بنا به لول ۱۰',en:'A building to Lv.10'},goal:10,stat:'maxBuild',reward:{gems:300}},
  // Items
  {id:'a_item5',cat:'item',name:{fa:'۵ آیتم',en:'5 Items'},desc:{fa:'۵ آیتم جمع کن',en:'Collect 5 items'},goal:5,stat:'itemCount',reward:{gold:300}},
  {id:'a_item25',cat:'item',name:{fa:'۲۵ آیتم',en:'25 Items'},desc:{fa:'۲۵ آیتم جمع کن',en:'Collect 25 items'},goal:25,stat:'itemCount',reward:{gems:100}},
  {id:'a_legItem',cat:'item',name:{fa:'اولین آیتم افسانه‌ای',en:'First Legendary'},desc:{fa:'یک آیتم افسانه‌ای بگیر',en:'Get a Legendary item'},goal:1,stat:'legItems',reward:{gems:200}},
  {id:'a_equip5',cat:'item',name:{fa:'۵ تجهیز',en:'5 Equips'},desc:{fa:'۵ بار آیتم تجهیز کن',en:'Equip items 5 times'},goal:5,stat:'equips',reward:{gold:500}},
  {id:'a_fullEquip',cat:'item',name:{fa:'تجهیزات کامل',en:'Fully Equipped'},desc:{fa:'یک قهرمان با ۵ اسلات پر',en:'Hero with 5 slots filled'},goal:1,stat:'fullEquipHero',reward:{gems:150}},
  // Minigames
  {id:'a_mini1',cat:'mini',name:{fa:'اولین مینی‌گیم',en:'First Minigame'},desc:{fa:'یک مینی‌گیم بازی کن',en:'Play a minigame'},goal:1,stat:'minigames',reward:{gems:20}},
  {id:'a_mini10',cat:'mini',name:{fa:'۱۰ مینی‌گیم',en:'Minigame Fan'},desc:{fa:'۱۰ بار مینی‌گیم بازی کن',en:'Play 10 minigames'},goal:10,stat:'minigames',reward:{gems:100}},
  {id:'a_archer100',cat:'mini',name:{fa:'استاد کمان',en:'Master Archer'},desc:{fa:'در مسابقه کمانگیری ۱۰۰ امتیاز',en:'Score 100 in archery'},goal:100,stat:'archeryHigh',reward:{gems:150,item:'kaman_arash'}},
  {id:'a_horse10',cat:'mini',name:{fa:'سوارکار ماهر',en:'Skilled Rider'},desc:{fa:'در مسابقه رخش ۱۰ بار برنده شو',en:'Win Rakhsh race 10 times'},goal:10,stat:'raceWins',reward:{gems:200}},
  {id:'a_forge25',cat:'mini',name:{fa:'استاد آهنگر',en:'Master Blacksmith'},desc:{fa:'۲۵ آیتم بساز',en:'Forge 25 items'},goal:25,stat:'forges',reward:{gems:300,item:'sword_shahi'}},
  // Special
  {id:'a_day3',cat:'special',name:{fa:'۳ روز پیاپی',en:'3-Day Streak'},desc:{fa:'۳ روز پیاپی وارد شو',en:'Login 3 days in a row'},goal:3,stat:'streak',reward:{gems:50}},
  {id:'a_day7',cat:'special',name:{fa:'۷ روز پیاپی',en:'Week Streak'},desc:{fa:'۷ روز پیاپی',en:'7-day streak'},goal:7,stat:'streak',reward:{gems:150,scrolls:5}},
  {id:'a_day30',cat:'special',name:{fa:'۳۰ روز پیاپی',en:'Month Streak'},desc:{fa:'۳۰ روز پیاپی',en:'30-day streak'},goal:30,stat:'streak',reward:{gems:1000,item:'taj_kiani'}},
  {id:'a_pet1',cat:'special',name:{fa:'اولین پت',en:'First Pet'},desc:{fa:'یک پت به دست آور',en:'Get a pet'},goal:1,stat:'petCount',reward:{gems:100}},
  {id:'a_petAll',cat:'special',name:{fa:'همه پت‌ها',en:'Pet Master'},desc:{fa:'همه ۳ پت را جمع کن',en:'Get all 3 pets'},goal:3,stat:'petCount',reward:{gems:500}},
  {id:'a_rostam',cat:'special',name:{fa:'رستم را احضار کن',en:'Summon Rostam'},desc:{fa:'رستم دستان را به دست آور',en:'Get Rostam'},goal:1,stat:'hasRostam',reward:{gems:200}},
  {id:'a_lang',cat:'special',name:{fa:'دوزبانه',en:'Bilingual'},desc:{fa:'زبان را تغییر بده',en:'Change language'},goal:1,stat:'langSwitch',reward:{gems:10}},
  {id:'a_settings',cat:'special',name:{fa:'خانه‌آرا',en:'Home Decorator'},desc:{fa:'یک بنا بساز',en:'Build once'},goal:1,stat:'builds',reward:{gold:100}},
  {id:'a_5minPlay',cat:'special',name:{fa:'۵ دقیقه بازی',en:'5 Minutes'},desc:{fa:'۵ دقیقه بازی کن',en:'Play for 5 minutes'},goal:300,stat:'playTime',reward:{gold:200}},
  {id:'a_1hour',cat:'special',name:{fa:'یک ساعت بازی',en:'1 Hour'},desc:{fa:'۱ ساعت بازی کن',en:'Play for 1 hour'},goal:3600,stat:'playTime',reward:{gems:100}},
  {id:'a_10hour',cat:'special',name:{fa:'ده ساعت بازی',en:'10 Hours'},desc:{fa:'۱۰ ساعت بازی کن',en:'Play 10 hours'},goal:36000,stat:'playTime',reward:{gems:500,item:'shamshir_shahi'}},
];

// ---------------- MINIGAMES ----------------
const MINIGAMES = [
  {id:'archery',name:{fa:'کمانگیری آرش',en:'Arash Archery'},icon:'🏹',
    desc:{fa:'با تیراندازی به هدف امتیاز جمع کن!',en:'Hit targets to score!'}},
  {id:'race',name:{fa:'مسابقه رخش',en:'Rakhsh Race'},icon:'🐎',
    desc:{fa:'با رخش از موانع بپر و برنده شو!',en:'Race Rakhsh and dodge obstacles!'}},
  {id:'forge',name:{fa:'آهنگری کاوه',en:'Kavehs Forge'},icon:'🔨',
    desc:{fa:'در زمان مناسب کوبیدن کن تا آیتم بسازی!',en:'Hammer at the right time to forge!'}},
];
