// Expanded ITEMS array — 50 items per category (350 total)
const EXPANDED_ITEMS = [
  {id:'weapon_sword_01',type:'weapon',rarity:'Common',name:{fa:'weapon Sword 01',en:'Weapon Sword 01'},atk:6,hero:'rostam'},
  {id:'weapon_sword_02',type:'weapon',rarity:'Rare',name:{fa:'weapon Sword 02',en:'Weapon Sword 02'},atk:6,hero:'arash'},
  {id:'weapon_axe_01',type:'weapon',rarity:'Epic',name:{fa:'weapon Axe 01',en:'Weapon Axe 01'},atk:6,hero:'fereydun'},
  {id:'weapon_bow_01',type:'weapon',rarity:'Legendary',name:{fa:'weapon Bow 01',en:'Weapon Bow 01'},atk:6,hero:'garshasp'},
  {id:'weapon_spear_01',type:'weapon',rarity:'Common',name:{fa:'weapon Spear 01',en:'Weapon Spear 01'},atk:6,hero:'rostam'},
  {id:'weapon_mace_01',type:'weapon',rarity:'Rare',name:{fa:'weapon Mace 01',en:'Weapon Mace 01'},atk:14,hero:'arash'},
  {id:'weapon_dagger_01',type:'weapon',rarity:'Epic',name:{fa:'weapon Dagger 01',en:'Weapon Dagger 01'},atk:14,hero:'fereydun'},
  {id:'weapon_hammer_01',type:'weapon',rarity:'Legendary',name:{fa:'weapon Hammer 01',en:'Weapon Hammer 01'},atk:14,hero:'garshasp'},
  {id:'weapon_lance_01',type:'weapon',rarity:'Rare',name:{fa:'weapon Lance 01',en:'Weapon Lance 01'},atk:14,hero:'rostam'},
  {id:'weapon_staff_01',type:'weapon',rarity:'Epic',name:{fa:'weapon Staff 01',en:'Weapon Staff 01'},atk:14,hero:'arash'},
  {id:'weapon_11',type:'weapon',rarity:'Common',name:{fa:'weapon 11',en:'Weapon 11'},atk:22},
  {id:'weapon_12',type:'weapon',rarity:'Rare',name:{fa:'weapon 12',en:'Weapon 12'},atk:22},
  {id:'weapon_13',type:'weapon',rarity:'Epic',name:{fa:'weapon 13',en:'Weapon 13'},atk:22},
  {id:'weapon_14',type:'weapon',rarity:'Legendary',name:{fa:'weapon 14',en:'Weapon 14'},atk:22},
  {id:'weapon_15',type:'weapon',rarity:'Common',name:{fa:'weapon 15',en:'Weapon 15'},atk:22},
  {id:'weapon_16',type:'weapon',rarity:'Rare',name:{fa:'weapon 16',en:'Weapon 16'},atk:30},
  {id:'weapon_17',type:'weapon',rarity:'Epic',name:{fa:'weapon 17',en:'Weapon 17'},atk:30},
  {id:'weapon_18',type:'weapon',rarity:'Legendary',name:{fa:'weapon 18',en:'Weapon 18'},atk:30},
  {id:'weapon_19',type:'weapon',rarity:'Rare',name:{fa:'weapon 19',en:'Weapon 19'},atk:30},
  {id:'weapon_20',type:'weapon',rarity:'Epic',name:{fa:'weapon 20',en:'Weapon 20'},atk:30},
  {id:'weapon_21',type:'weapon',rarity:'Common',name:{fa:'weapon 21',en:'Weapon 21'},atk:38},
  {id:'weapon_22',type:'weapon',rarity:'Rare',name:{fa:'weapon 22',en:'Weapon 22'},atk:38},
  {id:'weapon_23',type:'weapon',rarity:'Epic',name:{fa:'weapon 23',en:'Weapon 23'},atk:38},
  {id:'weapon_24',type:'weapon',rarity:'Legendary',name:{fa:'weapon 24',en:'Weapon 24'},atk:38},
  {id:'weapon_25',type:'weapon',rarity:'Common',name:{fa:'weapon 25',en:'Weapon 25'},atk:38},
  {id:'weapon_26',type:'weapon',rarity:'Rare',name:{fa:'weapon 26',en:'Weapon 26'},atk:46},
  {id:'weapon_27',type:'weapon',rarity:'Epic',name:{fa:'weapon 27',en:'Weapon 27'},atk:46},
  {id:'weapon_28',type:'weapon',rarity:'Legendary',name:{fa:'weapon 28',en:'Weapon 28'},atk:46},
  {id:'weapon_29',type:'weapon',rarity:'Rare',name:{fa:'weapon 29',en:'Weapon 29'},atk:46},
  {id:'weapon_30',type:'weapon',rarity:'Epic',name:{fa:'weapon 30',en:'Weapon 30'},atk:46},
  {id:'weapon_31',type:'weapon',rarity:'Common',name:{fa:'weapon 31',en:'Weapon 31'},atk:54},
  {id:'weapon_32',type:'weapon',rarity:'Rare',name:{fa:'weapon 32',en:'Weapon 32'},atk:54},
  {id:'weapon_33',type:'weapon',rarity:'Epic',name:{fa:'weapon 33',en:'Weapon 33'},atk:54},
  {id:'weapon_34',type:'weapon',rarity:'Legendary',name:{fa:'weapon 34',en:'Weapon 34'},atk:54},
  {id:'weapon_35',type:'weapon',rarity:'Common',name:{fa:'weapon 35',en:'Weapon 35'},atk:54},
  {id:'weapon_36',type:'weapon',rarity:'Rare',name:{fa:'weapon 36',en:'Weapon 36'},atk:62},
  {id:'weapon_37',type:'weapon',rarity:'Epic',name:{fa:'weapon 37',en:'Weapon 37'},atk:62,crit:8},
  {id:'weapon_38',type:'weapon',rarity:'Legendary',name:{fa:'weapon 38',en:'Weapon 38'},atk:62,crit:11},
  {id:'weapon_39',type:'weapon',rarity:'Rare',name:{fa:'weapon 39',en:'Weapon 39'},atk:62,crit:14},
  {id:'weapon_40',type:'weapon',rarity:'Epic',name:{fa:'weapon 40',en:'Weapon 40'},atk:62,crit:17},
  {id:'weapon_41',type:'weapon',rarity:'Common',name:{fa:'weapon 41',en:'Weapon 41'},atk:70,crit:5},
  {id:'weapon_42',type:'weapon',rarity:'Rare',name:{fa:'weapon 42',en:'Weapon 42'},atk:70,crit:8},
  {id:'weapon_43',type:'weapon',rarity:'Epic',name:{fa:'weapon 43',en:'Weapon 43'},atk:70,crit:11},
  {id:'weapon_44',type:'weapon',rarity:'Legendary',name:{fa:'weapon 44',en:'Weapon 44'},atk:70,crit:14},
  {id:'weapon_45',type:'weapon',rarity:'Common',name:{fa:'weapon 45',en:'Weapon 45'},atk:70,crit:17},
  {id:'weapon_46',type:'weapon',rarity:'Rare',name:{fa:'weapon 46',en:'Weapon 46'},atk:78,crit:5},
  {id:'weapon_47',type:'weapon',rarity:'Epic',name:{fa:'weapon 47',en:'Weapon 47'},atk:78,crit:8},
  {id:'weapon_48',type:'weapon',rarity:'Legendary',name:{fa:'weapon 48',en:'Weapon 48'},atk:78,crit:11},
  {id:'weapon_49',type:'weapon',rarity:'Rare',name:{fa:'weapon 49',en:'Weapon 49'},atk:78,crit:14},
  {id:'weapon_50',type:'weapon',rarity:'Epic',name:{fa:'weapon 50',en:'Weapon 50'},atk:78,crit:17},
  {id:'helm_leather_01',type:'helm',rarity:'Common',name:{fa:'helm Leather 01',en:'Helm Leather 01'},def:4,hp:10,hero:'rostam'},
  {id:'helm_bronze_01',type:'helm',rarity:'Rare',name:{fa:'helm Bronze 01',en:'Helm Bronze 01'},def:4,hp:10,hero:'arash'},
  {id:'helm_steel_01',type:'helm',rarity:'Epic',name:{fa:'helm Steel 01',en:'Helm Steel 01'},def:4,hp:10,hero:'fereydun'},
  {id:'helm_gold_01',type:'helm',rarity:'Legendary',name:{fa:'helm Gold 01',en:'Helm Gold 01'},def:4,hp:10,hero:'garshasp'},
  {id:'helm_crown_01',type:'helm',rarity:'Common',name:{fa:'helm Crown 01',en:'Helm Crown 01'},def:4,hp:10,hero:'rostam'},
  {id:'helm_royal_01',type:'helm',rarity:'Rare',name:{fa:'helm Royal 01',en:'Helm Royal 01'},def:8,hp:25,hero:'arash'},
  {id:'helm_dark_01',type:'helm',rarity:'Epic',name:{fa:'helm Dark 01',en:'Helm Dark 01'},def:8,hp:25,hero:'fereydun'},
  {id:'helm_legend_01',type:'helm',rarity:'Legendary',name:{fa:'helm Legend 01',en:'Helm Legend 01'},def:8,hp:25,hero:'garshasp'},
  {id:'helm_ancient_01',type:'helm',rarity:'Rare',name:{fa:'helm Ancient 01',en:'Helm Ancient 01'},def:8,hp:25,hero:'rostam'},
  {id:'helm_divine_01',type:'helm',rarity:'Epic',name:{fa:'helm Divine 01',en:'Helm Divine 01'},def:8,hp:25,hero:'arash'},
  {id:'helm_11',type:'helm',rarity:'Common',name:{fa:'helm 11',en:'Helm 11'},def:12,hp:40},
  {id:'helm_12',type:'helm',rarity:'Rare',name:{fa:'helm 12',en:'Helm 12'},def:12,hp:40},
  {id:'helm_13',type:'helm',rarity:'Epic',name:{fa:'helm 13',en:'Helm 13'},def:12,hp:40},
  {id:'helm_14',type:'helm',rarity:'Legendary',name:{fa:'helm 14',en:'Helm 14'},def:12,hp:40},
  {id:'helm_15',type:'helm',rarity:'Common',name:{fa:'helm 15',en:'Helm 15'},def:12,hp:40},
  {id:'helm_16',type:'helm',rarity:'Rare',name:{fa:'helm 16',en:'Helm 16'},def:16,hp:55},
  {id:'helm_17',type:'helm',rarity:'Epic',name:{fa:'helm 17',en:'Helm 17'},def:16,hp:55},
  {id:'helm_18',type:'helm',rarity:'Legendary',name:{fa:'helm 18',en:'Helm 18'},def:16,hp:55},
  {id:'helm_19',type:'helm',rarity:'Rare',name:{fa:'helm 19',en:'Helm 19'},def:16,hp:55},
  {id:'helm_20',type:'helm',rarity:'Epic',name:{fa:'helm 20',en:'Helm 20'},def:16,hp:55},
  {id:'helm_21',type:'helm',rarity:'Common',name:{fa:'helm 21',en:'Helm 21'},def:20,hp:70},
  {id:'helm_22',type:'helm',rarity:'Rare',name:{fa:'helm 22',en:'Helm 22'},def:20,hp:70,atk:2},
  {id:'helm_23',type:'helm',rarity:'Epic',name:{fa:'helm 23',en:'Helm 23'},def:20,hp:70,atk:3},
  {id:'helm_24',type:'helm',rarity:'Legendary',name:{fa:'helm 24',en:'Helm 24'},def:20,hp:70,atk:4},
  {id:'helm_25',type:'helm',rarity:'Common',name:{fa:'helm 25',en:'Helm 25'},def:20,hp:70,atk:2},
  {id:'helm_26',type:'helm',rarity:'Rare',name:{fa:'helm 26',en:'Helm 26'},def:24,hp:85,atk:3},
  {id:'helm_27',type:'helm',rarity:'Epic',name:{fa:'helm 27',en:'Helm 27'},def:24,hp:85,atk:4},
  {id:'helm_28',type:'helm',rarity:'Legendary',name:{fa:'helm 28',en:'Helm 28'},def:24,hp:85,atk:2},
  {id:'helm_29',type:'helm',rarity:'Rare',name:{fa:'helm 29',en:'Helm 29'},def:24,hp:85,atk:3},
  {id:'helm_30',type:'helm',rarity:'Epic',name:{fa:'helm 30',en:'Helm 30'},def:24,hp:85,atk:4},
  {id:'helm_31',type:'helm',rarity:'Common',name:{fa:'helm 31',en:'Helm 31'},def:28,hp:100,atk:2},
  {id:'helm_32',type:'helm',rarity:'Rare',name:{fa:'helm 32',en:'Helm 32'},def:28,hp:100,atk:3},
  {id:'helm_33',type:'helm',rarity:'Epic',name:{fa:'helm 33',en:'Helm 33'},def:28,hp:100,atk:4},
  {id:'helm_34',type:'helm',rarity:'Legendary',name:{fa:'helm 34',en:'Helm 34'},def:28,hp:100,atk:2},
  {id:'helm_35',type:'helm',rarity:'Common',name:{fa:'helm 35',en:'Helm 35'},def:28,hp:100,atk:3},
  {id:'helm_36',type:'helm',rarity:'Rare',name:{fa:'helm 36',en:'Helm 36'},def:32,hp:115,atk:4},
  {id:'helm_37',type:'helm',rarity:'Epic',name:{fa:'helm 37',en:'Helm 37'},def:32,hp:115,atk:2},
  {id:'helm_38',type:'helm',rarity:'Legendary',name:{fa:'helm 38',en:'Helm 38'},def:32,hp:115,atk:3},
  {id:'helm_39',type:'helm',rarity:'Rare',name:{fa:'helm 39',en:'Helm 39'},def:32,hp:115,atk:4},
  {id:'helm_40',type:'helm',rarity:'Epic',name:{fa:'helm 40',en:'Helm 40'},def:32,hp:115,atk:2},
  {id:'helm_41',type:'helm',rarity:'Common',name:{fa:'helm 41',en:'Helm 41'},def:36,hp:130,atk:3},
  {id:'helm_42',type:'helm',rarity:'Rare',name:{fa:'helm 42',en:'Helm 42'},def:36,hp:130,atk:4},
  {id:'helm_43',type:'helm',rarity:'Epic',name:{fa:'helm 43',en:'Helm 43'},def:36,hp:130,atk:2},
  {id:'helm_44',type:'helm',rarity:'Legendary',name:{fa:'helm 44',en:'Helm 44'},def:36,hp:130,atk:3},
  {id:'helm_45',type:'helm',rarity:'Common',name:{fa:'helm 45',en:'Helm 45'},def:36,hp:130,atk:4},
  {id:'helm_46',type:'helm',rarity:'Rare',name:{fa:'helm 46',en:'Helm 46'},def:40,hp:145,atk:2},
  {id:'helm_47',type:'helm',rarity:'Epic',name:{fa:'helm 47',en:'Helm 47'},def:40,hp:145,atk:3},
  {id:'helm_48',type:'helm',rarity:'Legendary',name:{fa:'helm 48',en:'Helm 48'},def:40,hp:145,atk:4},
  {id:'helm_49',type:'helm',rarity:'Rare',name:{fa:'helm 49',en:'Helm 49'},def:40,hp:145,atk:2},
  {id:'helm_50',type:'helm',rarity:'Epic',name:{fa:'helm 50',en:'Helm 50'},def:40,hp:145,atk:3},
  {id:'armor_leather_01',type:'armor',rarity:'Common',name:{fa:'armor Leather 01',en:'Armor Leather 01'},def:10,hp:20,hero:'rostam'},
  {id:'armor_scale_01',type:'armor',rarity:'Rare',name:{fa:'armor Scale 01',en:'Armor Scale 01'},def:10,hp:20,hero:'arash'},
  {id:'armor_plate_01',type:'armor',rarity:'Epic',name:{fa:'armor Plate 01',en:'Armor Plate 01'},def:10,hp:20,hero:'fereydun'},
  {id:'armor_royal_01',type:'armor',rarity:'Legendary',name:{fa:'armor Royal 01',en:'Armor Royal 01'},def:10,hp:20,hero:'garshasp'},
  {id:'armor_legend_01',type:'armor',rarity:'Common',name:{fa:'armor Legend 01',en:'Armor Legend 01'},def:10,hp:20,hero:'rostam'},
  {id:'armor_tiger_01',type:'armor',rarity:'Rare',name:{fa:'armor Tiger 01',en:'Armor Tiger 01'},def:16,hp:40,hero:'arash'},
  {id:'armor_immortal_01',type:'armor',rarity:'Epic',name:{fa:'armor Immortal 01',en:'Armor Immortal 01'},def:16,hp:40,hero:'fereydun'},
  {id:'armor_dark_01',type:'armor',rarity:'Legendary',name:{fa:'armor Dark 01',en:'Armor Dark 01'},def:16,hp:40,hero:'garshasp'},
  {id:'armor_golden_01',type:'armor',rarity:'Rare',name:{fa:'armor Golden 01',en:'Armor Golden 01'},def:16,hp:40,hero:'rostam'},
  {id:'armor_divine_01',type:'armor',rarity:'Epic',name:{fa:'armor Divine 01',en:'Armor Divine 01'},def:16,hp:40,hero:'arash'},
  {id:'armor_11',type:'armor',rarity:'Common',name:{fa:'armor 11',en:'Armor 11'},def:22,hp:60},
  {id:'armor_12',type:'armor',rarity:'Rare',name:{fa:'armor 12',en:'Armor 12'},def:22,hp:60},
  {id:'armor_13',type:'armor',rarity:'Epic',name:{fa:'armor 13',en:'Armor 13'},def:22,hp:60},
  {id:'armor_14',type:'armor',rarity:'Legendary',name:{fa:'armor 14',en:'Armor 14'},def:22,hp:60},
  {id:'armor_15',type:'armor',rarity:'Common',name:{fa:'armor 15',en:'Armor 15'},def:22,hp:60},
  {id:'armor_16',type:'armor',rarity:'Rare',name:{fa:'armor 16',en:'Armor 16'},def:28,hp:80},
  {id:'armor_17',type:'armor',rarity:'Epic',name:{fa:'armor 17',en:'Armor 17'},def:28,hp:80},
  {id:'armor_18',type:'armor',rarity:'Legendary',name:{fa:'armor 18',en:'Armor 18'},def:28,hp:80},
  {id:'armor_19',type:'armor',rarity:'Rare',name:{fa:'armor 19',en:'Armor 19'},def:28,hp:80},
  {id:'armor_20',type:'armor',rarity:'Epic',name:{fa:'armor 20',en:'Armor 20'},def:28,hp:80},
  {id:'armor_21',type:'armor',rarity:'Common',name:{fa:'armor 21',en:'Armor 21'},def:34,hp:100},
  {id:'armor_22',type:'armor',rarity:'Rare',name:{fa:'armor 22',en:'Armor 22'},def:34,hp:100},
  {id:'armor_23',type:'armor',rarity:'Epic',name:{fa:'armor 23',en:'Armor 23'},def:34,hp:100},
  {id:'armor_24',type:'armor',rarity:'Legendary',name:{fa:'armor 24',en:'Armor 24'},def:34,hp:100},
  {id:'armor_25',type:'armor',rarity:'Common',name:{fa:'armor 25',en:'Armor 25'},def:34,hp:100},
  {id:'armor_26',type:'armor',rarity:'Rare',name:{fa:'armor 26',en:'Armor 26'},def:40,hp:120},
  {id:'armor_27',type:'armor',rarity:'Epic',name:{fa:'armor 27',en:'Armor 27'},def:40,hp:120},
  {id:'armor_28',type:'armor',rarity:'Legendary',name:{fa:'armor 28',en:'Armor 28'},def:40,hp:120},
  {id:'armor_29',type:'armor',rarity:'Rare',name:{fa:'armor 29',en:'Armor 29'},def:40,hp:120},
  {id:'armor_30',type:'armor',rarity:'Epic',name:{fa:'armor 30',en:'Armor 30'},def:40,hp:120},
  {id:'armor_31',type:'armor',rarity:'Common',name:{fa:'armor 31',en:'Armor 31'},def:46,hp:140},
  {id:'armor_32',type:'armor',rarity:'Rare',name:{fa:'armor 32',en:'Armor 32'},def:46,hp:140,atk:7},
  {id:'armor_33',type:'armor',rarity:'Epic',name:{fa:'armor 33',en:'Armor 33'},def:46,hp:140,atk:4},
  {id:'armor_34',type:'armor',rarity:'Legendary',name:{fa:'armor 34',en:'Armor 34'},def:46,hp:140,atk:5},
  {id:'armor_35',type:'armor',rarity:'Common',name:{fa:'armor 35',en:'Armor 35'},def:46,hp:140,atk:6},
  {id:'armor_36',type:'armor',rarity:'Rare',name:{fa:'armor 36',en:'Armor 36'},def:52,hp:160,atk:7},
  {id:'armor_37',type:'armor',rarity:'Epic',name:{fa:'armor 37',en:'Armor 37'},def:52,hp:160,atk:4},
  {id:'armor_38',type:'armor',rarity:'Legendary',name:{fa:'armor 38',en:'Armor 38'},def:52,hp:160,atk:5},
  {id:'armor_39',type:'armor',rarity:'Rare',name:{fa:'armor 39',en:'Armor 39'},def:52,hp:160,atk:6},
  {id:'armor_40',type:'armor',rarity:'Epic',name:{fa:'armor 40',en:'Armor 40'},def:52,hp:160,atk:7},
  {id:'armor_41',type:'armor',rarity:'Common',name:{fa:'armor 41',en:'Armor 41'},def:58,hp:180,atk:4},
  {id:'armor_42',type:'armor',rarity:'Rare',name:{fa:'armor 42',en:'Armor 42'},def:58,hp:180,atk:5},
  {id:'armor_43',type:'armor',rarity:'Epic',name:{fa:'armor 43',en:'Armor 43'},def:58,hp:180,atk:6},
  {id:'armor_44',type:'armor',rarity:'Legendary',name:{fa:'armor 44',en:'Armor 44'},def:58,hp:180,atk:7},
  {id:'armor_45',type:'armor',rarity:'Common',name:{fa:'armor 45',en:'Armor 45'},def:58,hp:180,atk:4},
  {id:'armor_46',type:'armor',rarity:'Rare',name:{fa:'armor 46',en:'Armor 46'},def:64,hp:200,atk:5},
  {id:'armor_47',type:'armor',rarity:'Epic',name:{fa:'armor 47',en:'Armor 47'},def:64,hp:200,atk:6},
  {id:'armor_48',type:'armor',rarity:'Legendary',name:{fa:'armor 48',en:'Armor 48'},def:64,hp:200,atk:7},
  {id:'armor_49',type:'armor',rarity:'Rare',name:{fa:'armor 49',en:'Armor 49'},def:64,hp:200,atk:4},
  {id:'armor_50',type:'armor',rarity:'Epic',name:{fa:'armor 50',en:'Armor 50'},def:64,hp:200,atk:5},
  {id:'boots_leather_01',type:'boots',rarity:'Common',name:{fa:'boots Leather 01',en:'Boots Leather 01'},def:2,spd:1,hero:'rostam'},
  {id:'boots_steel_01',type:'boots',rarity:'Rare',name:{fa:'boots Steel 01',en:'Boots Steel 01'},def:2,spd:1,hero:'arash'},
  {id:'boots_royal_01',type:'boots',rarity:'Epic',name:{fa:'boots Royal 01',en:'Boots Royal 01'},def:2,spd:1,hero:'fereydun'},
  {id:'boots_legend_01',type:'boots',rarity:'Legendary',name:{fa:'boots Legend 01',en:'Boots Legend 01'},def:2,spd:3,hero:'garshasp'},
  {id:'boots_divine_01',type:'boots',rarity:'Common',name:{fa:'boots Divine 01',en:'Boots Divine 01'},def:2,spd:3,hero:'rostam'},
  {id:'boots_race_01',type:'boots',rarity:'Rare',name:{fa:'boots Race 01',en:'Boots Race 01'},def:5,spd:3,hero:'arash'},
  {id:'boots_war_01',type:'boots',rarity:'Epic',name:{fa:'boots War 01',en:'Boots War 01'},def:5,spd:5,hero:'fereydun'},
  {id:'boots_magic_01',type:'boots',rarity:'Legendary',name:{fa:'boots Magic 01',en:'Boots Magic 01'},def:5,spd:5,hero:'garshasp'},
  {id:'boots_ancient_01',type:'boots',rarity:'Rare',name:{fa:'boots Ancient 01',en:'Boots Ancient 01'},def:5,spd:5,hero:'rostam'},
  {id:'boots_shadow_01',type:'boots',rarity:'Epic',name:{fa:'boots Shadow 01',en:'Boots Shadow 01'},def:5,spd:7,hero:'arash'},
  {id:'boots_11',type:'boots',rarity:'Common',name:{fa:'boots 11',en:'Boots 11'},def:8,spd:7},
  {id:'boots_12',type:'boots',rarity:'Rare',name:{fa:'boots 12',en:'Boots 12'},def:8,spd:7},
  {id:'boots_13',type:'boots',rarity:'Epic',name:{fa:'boots 13',en:'Boots 13'},def:8,spd:9},
  {id:'boots_14',type:'boots',rarity:'Legendary',name:{fa:'boots 14',en:'Boots 14'},def:8,spd:9},
  {id:'boots_15',type:'boots',rarity:'Common',name:{fa:'boots 15',en:'Boots 15'},def:8,spd:9},
  {id:'boots_16',type:'boots',rarity:'Rare',name:{fa:'boots 16',en:'Boots 16'},def:11,spd:11},
  {id:'boots_17',type:'boots',rarity:'Epic',name:{fa:'boots 17',en:'Boots 17'},def:11,spd:11},
  {id:'boots_18',type:'boots',rarity:'Legendary',name:{fa:'boots 18',en:'Boots 18'},def:11,spd:11},
  {id:'boots_19',type:'boots',rarity:'Rare',name:{fa:'boots 19',en:'Boots 19'},def:11,spd:13},
  {id:'boots_20',type:'boots',rarity:'Epic',name:{fa:'boots 20',en:'Boots 20'},def:11,spd:13},
  {id:'boots_21',type:'boots',rarity:'Common',name:{fa:'boots 21',en:'Boots 21'},def:14,spd:13},
  {id:'boots_22',type:'boots',rarity:'Rare',name:{fa:'boots 22',en:'Boots 22'},def:14,spd:15},
  {id:'boots_23',type:'boots',rarity:'Epic',name:{fa:'boots 23',en:'Boots 23'},def:14,spd:15},
  {id:'boots_24',type:'boots',rarity:'Legendary',name:{fa:'boots 24',en:'Boots 24'},def:14,spd:15},
  {id:'boots_25',type:'boots',rarity:'Common',name:{fa:'boots 25',en:'Boots 25'},def:14,spd:17},
  {id:'boots_26',type:'boots',rarity:'Rare',name:{fa:'boots 26',en:'Boots 26'},def:17,spd:17},
  {id:'boots_27',type:'boots',rarity:'Epic',name:{fa:'boots 27',en:'Boots 27'},def:17,spd:17,hp:15},
  {id:'boots_28',type:'boots',rarity:'Legendary',name:{fa:'boots 28',en:'Boots 28'},def:17,spd:19,hp:20},
  {id:'boots_29',type:'boots',rarity:'Rare',name:{fa:'boots 29',en:'Boots 29'},def:17,spd:19,hp:25},
  {id:'boots_30',type:'boots',rarity:'Epic',name:{fa:'boots 30',en:'Boots 30'},def:17,spd:19,hp:30},
  {id:'boots_31',type:'boots',rarity:'Common',name:{fa:'boots 31',en:'Boots 31'},def:20,spd:21,hp:10},
  {id:'boots_32',type:'boots',rarity:'Rare',name:{fa:'boots 32',en:'Boots 32'},def:20,spd:21,hp:15},
  {id:'boots_33',type:'boots',rarity:'Epic',name:{fa:'boots 33',en:'Boots 33'},def:20,spd:21,hp:20},
  {id:'boots_34',type:'boots',rarity:'Legendary',name:{fa:'boots 34',en:'Boots 34'},def:20,spd:23,hp:25},
  {id:'boots_35',type:'boots',rarity:'Common',name:{fa:'boots 35',en:'Boots 35'},def:20,spd:23,hp:30},
  {id:'boots_36',type:'boots',rarity:'Rare',name:{fa:'boots 36',en:'Boots 36'},def:23,spd:23,hp:10},
  {id:'boots_37',type:'boots',rarity:'Epic',name:{fa:'boots 37',en:'Boots 37'},def:23,spd:25,hp:15},
  {id:'boots_38',type:'boots',rarity:'Legendary',name:{fa:'boots 38',en:'Boots 38'},def:23,spd:25,hp:20},
  {id:'boots_39',type:'boots',rarity:'Rare',name:{fa:'boots 39',en:'Boots 39'},def:23,spd:25,hp:25},
  {id:'boots_40',type:'boots',rarity:'Epic',name:{fa:'boots 40',en:'Boots 40'},def:23,spd:27,hp:30},
  {id:'boots_41',type:'boots',rarity:'Common',name:{fa:'boots 41',en:'Boots 41'},def:26,spd:27,hp:10},
  {id:'boots_42',type:'boots',rarity:'Rare',name:{fa:'boots 42',en:'Boots 42'},def:26,spd:27,hp:15},
  {id:'boots_43',type:'boots',rarity:'Epic',name:{fa:'boots 43',en:'Boots 43'},def:26,spd:29,hp:20},
  {id:'boots_44',type:'boots',rarity:'Legendary',name:{fa:'boots 44',en:'Boots 44'},def:26,spd:29,hp:25},
  {id:'boots_45',type:'boots',rarity:'Common',name:{fa:'boots 45',en:'Boots 45'},def:26,spd:29,hp:30},
  {id:'boots_46',type:'boots',rarity:'Rare',name:{fa:'boots 46',en:'Boots 46'},def:29,spd:31,hp:10},
  {id:'boots_47',type:'boots',rarity:'Epic',name:{fa:'boots 47',en:'Boots 47'},def:29,spd:31,hp:15},
  {id:'boots_48',type:'boots',rarity:'Legendary',name:{fa:'boots 48',en:'Boots 48'},def:29,spd:31,hp:20},
  {id:'boots_49',type:'boots',rarity:'Rare',name:{fa:'boots 49',en:'Boots 49'},def:29,spd:33,hp:25},
  {id:'boots_50',type:'boots',rarity:'Epic',name:{fa:'boots 50',en:'Boots 50'},def:29,spd:33,hp:30},
  {id:'ring_bronze_01',type:'ring',rarity:'Common',name:{fa:'ring Bronze 01',en:'Ring Bronze 01'},atk:4,hero:'rostam'},
  {id:'ring_silver_01',type:'ring',rarity:'Rare',name:{fa:'ring Silver 01',en:'Ring Silver 01'},atk:4,hero:'arash'},
  {id:'ring_gold_01',type:'ring',rarity:'Epic',name:{fa:'ring Gold 01',en:'Ring Gold 01'},atk:4,hero:'fereydun'},
  {id:'ring_ruby_01',type:'ring',rarity:'Legendary',name:{fa:'ring Ruby 01',en:'Ring Ruby 01'},atk:4,hero:'garshasp'},
  {id:'ring_emerald_01',type:'ring',rarity:'Common',name:{fa:'ring Emerald 01',en:'Ring Emerald 01'},atk:4,hero:'rostam'},
  {id:'ring_turquoise_01',type:'ring',rarity:'Rare',name:{fa:'ring Turquoise 01',en:'Ring Turquoise 01'},atk:10,hero:'arash'},
  {id:'ring_sapphire_01',type:'ring',rarity:'Epic',name:{fa:'ring Sapphire 01',en:'Ring Sapphire 01'},atk:10,hero:'fereydun'},
  {id:'ring_amethyst_01',type:'ring',rarity:'Legendary',name:{fa:'ring Amethyst 01',en:'Ring Amethyst 01'},atk:10,hero:'garshasp'},
  {id:'ring_legend_01',type:'ring',rarity:'Rare',name:{fa:'ring Legend 01',en:'Ring Legend 01'},atk:10,hero:'rostam'},
  {id:'ring_divine_01',type:'ring',rarity:'Epic',name:{fa:'ring Divine 01',en:'Ring Divine 01'},atk:10,hero:'arash'},
  {id:'ring_11',type:'ring',rarity:'Common',name:{fa:'ring 11',en:'Ring 11'},atk:16},
  {id:'ring_12',type:'ring',rarity:'Rare',name:{fa:'ring 12',en:'Ring 12'},atk:16,def:4},
  {id:'ring_13',type:'ring',rarity:'Epic',name:{fa:'ring 13',en:'Ring 13'},atk:16,def:2},
  {id:'ring_14',type:'ring',rarity:'Legendary',name:{fa:'ring 14',en:'Ring 14'},atk:16,def:3},
  {id:'ring_15',type:'ring',rarity:'Common',name:{fa:'ring 15',en:'Ring 15'},atk:16,def:4},
  {id:'ring_16',type:'ring',rarity:'Rare',name:{fa:'ring 16',en:'Ring 16'},atk:22,def:2},
  {id:'ring_17',type:'ring',rarity:'Epic',name:{fa:'ring 17',en:'Ring 17'},atk:22,def:3},
  {id:'ring_18',type:'ring',rarity:'Legendary',name:{fa:'ring 18',en:'Ring 18'},atk:22,def:4},
  {id:'ring_19',type:'ring',rarity:'Rare',name:{fa:'ring 19',en:'Ring 19'},atk:22,def:2},
  {id:'ring_20',type:'ring',rarity:'Epic',name:{fa:'ring 20',en:'Ring 20'},atk:22,def:3},
  {id:'ring_21',type:'ring',rarity:'Common',name:{fa:'ring 21',en:'Ring 21'},atk:28,def:4},
  {id:'ring_22',type:'ring',rarity:'Rare',name:{fa:'ring 22',en:'Ring 22'},atk:28,crit:3,def:2},
  {id:'ring_23',type:'ring',rarity:'Epic',name:{fa:'ring 23',en:'Ring 23'},atk:28,crit:4,def:3},
  {id:'ring_24',type:'ring',rarity:'Legendary',name:{fa:'ring 24',en:'Ring 24'},atk:28,crit:5,def:4},
  {id:'ring_25',type:'ring',rarity:'Common',name:{fa:'ring 25',en:'Ring 25'},atk:28,crit:2,def:2},
  {id:'ring_26',type:'ring',rarity:'Rare',name:{fa:'ring 26',en:'Ring 26'},atk:34,crit:3,def:3},
  {id:'ring_27',type:'ring',rarity:'Epic',name:{fa:'ring 27',en:'Ring 27'},atk:34,crit:4,def:4},
  {id:'ring_28',type:'ring',rarity:'Legendary',name:{fa:'ring 28',en:'Ring 28'},atk:34,crit:5,def:2},
  {id:'ring_29',type:'ring',rarity:'Rare',name:{fa:'ring 29',en:'Ring 29'},atk:34,crit:2,def:3},
  {id:'ring_30',type:'ring',rarity:'Epic',name:{fa:'ring 30',en:'Ring 30'},atk:34,crit:3,def:4},
  {id:'ring_31',type:'ring',rarity:'Common',name:{fa:'ring 31',en:'Ring 31'},atk:40,crit:4,def:2},
  {id:'ring_32',type:'ring',rarity:'Rare',name:{fa:'ring 32',en:'Ring 32'},atk:40,crit:5,def:3},
  {id:'ring_33',type:'ring',rarity:'Epic',name:{fa:'ring 33',en:'Ring 33'},atk:40,crit:2,def:4},
  {id:'ring_34',type:'ring',rarity:'Legendary',name:{fa:'ring 34',en:'Ring 34'},atk:40,crit:3,def:2},
  {id:'ring_35',type:'ring',rarity:'Common',name:{fa:'ring 35',en:'Ring 35'},atk:40,crit:4,def:3},
  {id:'ring_36',type:'ring',rarity:'Rare',name:{fa:'ring 36',en:'Ring 36'},atk:46,crit:5,def:4},
  {id:'ring_37',type:'ring',rarity:'Epic',name:{fa:'ring 37',en:'Ring 37'},atk:46,crit:2,def:2},
  {id:'ring_38',type:'ring',rarity:'Legendary',name:{fa:'ring 38',en:'Ring 38'},atk:46,crit:3,def:3},
  {id:'ring_39',type:'ring',rarity:'Rare',name:{fa:'ring 39',en:'Ring 39'},atk:46,crit:4,def:4},
  {id:'ring_40',type:'ring',rarity:'Epic',name:{fa:'ring 40',en:'Ring 40'},atk:46,crit:5,def:2},
  {id:'ring_41',type:'ring',rarity:'Common',name:{fa:'ring 41',en:'Ring 41'},atk:52,crit:2,def:3},
  {id:'ring_42',type:'ring',rarity:'Rare',name:{fa:'ring 42',en:'Ring 42'},atk:52,crit:3,def:4},
  {id:'ring_43',type:'ring',rarity:'Epic',name:{fa:'ring 43',en:'Ring 43'},atk:52,crit:4,def:2},
  {id:'ring_44',type:'ring',rarity:'Legendary',name:{fa:'ring 44',en:'Ring 44'},atk:52,crit:5,def:3},
  {id:'ring_45',type:'ring',rarity:'Common',name:{fa:'ring 45',en:'Ring 45'},atk:52,crit:2,def:4},
  {id:'ring_46',type:'ring',rarity:'Rare',name:{fa:'ring 46',en:'Ring 46'},atk:58,crit:3,def:2},
  {id:'ring_47',type:'ring',rarity:'Epic',name:{fa:'ring 47',en:'Ring 47'},atk:58,crit:4,def:3},
  {id:'ring_48',type:'ring',rarity:'Legendary',name:{fa:'ring 48',en:'Ring 48'},atk:58,crit:5,def:4},
  {id:'ring_49',type:'ring',rarity:'Rare',name:{fa:'ring 49',en:'Ring 49'},atk:58,crit:2,def:2},
  {id:'ring_50',type:'ring',rarity:'Epic',name:{fa:'ring 50',en:'Ring 50'},atk:58,crit:3,def:3},
  {id:'necklace_amulet_01',type:'necklace',rarity:'Common',name:{fa:'necklace Amulet 01',en:'Necklace Amulet 01'},hp:15,def:3,hero:'rostam'},
  {id:'necklace_chain_01',type:'necklace',rarity:'Rare',name:{fa:'necklace Chain 01',en:'Necklace Chain 01'},hp:15,def:3,hero:'arash'},
  {id:'necklace_pendant_01',type:'necklace',rarity:'Epic',name:{fa:'necklace Pendant 01',en:'Necklace Pendant 01'},hp:15,def:3,hero:'fereydun'},
  {id:'necklace_golden_01',type:'necklace',rarity:'Legendary',name:{fa:'necklace Golden 01',en:'Necklace Golden 01'},hp:15,def:3,hero:'garshasp'},
  {id:'necklace_royal_01',type:'necklace',rarity:'Common',name:{fa:'necklace Royal 01',en:'Necklace Royal 01'},hp:15,def:3,hero:'rostam'},
  {id:'necklace_silver_01',type:'necklace',rarity:'Rare',name:{fa:'necklace Silver 01',en:'Necklace Silver 01'},hp:25,def:6,hero:'arash'},
  {id:'necklace_bronze_01',type:'necklace',rarity:'Epic',name:{fa:'necklace Bronze 01',en:'Necklace Bronze 01'},hp:25,def:6,hero:'fereydun'},
  {id:'necklace_crystal_01',type:'necklace',rarity:'Legendary',name:{fa:'necklace Crystal 01',en:'Necklace Crystal 01'},hp:25,def:6,hero:'garshasp'},
  {id:'necklace_shadow_01',type:'necklace',rarity:'Rare',name:{fa:'necklace Shadow 01',en:'Necklace Shadow 01'},hp:25,def:6,hero:'rostam'},
  {id:'necklace_divine_01',type:'necklace',rarity:'Epic',name:{fa:'necklace Divine 01',en:'Necklace Divine 01'},hp:25,def:6,hero:'arash'},
  {id:'necklace_11',type:'necklace',rarity:'Common',name:{fa:'necklace 11',en:'Necklace 11'},hp:35,def:9},
  {id:'necklace_12',type:'necklace',rarity:'Rare',name:{fa:'necklace 12',en:'Necklace 12'},hp:35,def:9},
  {id:'necklace_13',type:'necklace',rarity:'Epic',name:{fa:'necklace 13',en:'Necklace 13'},hp:35,def:9},
  {id:'necklace_14',type:'necklace',rarity:'Legendary',name:{fa:'necklace 14',en:'Necklace 14'},hp:35,def:9},
  {id:'necklace_15',type:'necklace',rarity:'Common',name:{fa:'necklace 15',en:'Necklace 15'},hp:35,def:9},
  {id:'necklace_16',type:'necklace',rarity:'Rare',name:{fa:'necklace 16',en:'Necklace 16'},hp:45,def:12},
  {id:'necklace_17',type:'necklace',rarity:'Epic',name:{fa:'necklace 17',en:'Necklace 17'},hp:45,def:12},
  {id:'necklace_18',type:'necklace',rarity:'Legendary',name:{fa:'necklace 18',en:'Necklace 18'},hp:45,def:12},
  {id:'necklace_19',type:'necklace',rarity:'Rare',name:{fa:'necklace 19',en:'Necklace 19'},hp:45,def:12},
  {id:'necklace_20',type:'necklace',rarity:'Epic',name:{fa:'necklace 20',en:'Necklace 20'},hp:45,def:12},
  {id:'necklace_21',type:'necklace',rarity:'Common',name:{fa:'necklace 21',en:'Necklace 21'},hp:55,def:15},
  {id:'necklace_22',type:'necklace',rarity:'Rare',name:{fa:'necklace 22',en:'Necklace 22'},hp:55,def:15},
  {id:'necklace_23',type:'necklace',rarity:'Epic',name:{fa:'necklace 23',en:'Necklace 23'},hp:55,def:15},
  {id:'necklace_24',type:'necklace',rarity:'Legendary',name:{fa:'necklace 24',en:'Necklace 24'},hp:55,def:15},
  {id:'necklace_25',type:'necklace',rarity:'Common',name:{fa:'necklace 25',en:'Necklace 25'},hp:55,def:15},
  {id:'necklace_26',type:'necklace',rarity:'Rare',name:{fa:'necklace 26',en:'Necklace 26'},hp:65,def:18},
  {id:'necklace_27',type:'necklace',rarity:'Epic',name:{fa:'necklace 27',en:'Necklace 27'},hp:65,def:18},
  {id:'necklace_28',type:'necklace',rarity:'Legendary',name:{fa:'necklace 28',en:'Necklace 28'},hp:65,def:18},
  {id:'necklace_29',type:'necklace',rarity:'Rare',name:{fa:'necklace 29',en:'Necklace 29'},hp:65,def:18},
  {id:'necklace_30',type:'necklace',rarity:'Epic',name:{fa:'necklace 30',en:'Necklace 30'},hp:65,def:18},
  {id:'necklace_31',type:'necklace',rarity:'Common',name:{fa:'necklace 31',en:'Necklace 31'},hp:75,def:21},
  {id:'necklace_32',type:'necklace',rarity:'Rare',name:{fa:'necklace 32',en:'Necklace 32'},hp:75,def:21,atk:6},
  {id:'necklace_33',type:'necklace',rarity:'Epic',name:{fa:'necklace 33',en:'Necklace 33'},hp:75,def:21,atk:7},
  {id:'necklace_34',type:'necklace',rarity:'Legendary',name:{fa:'necklace 34',en:'Necklace 34'},hp:75,def:21,atk:8},
  {id:'necklace_35',type:'necklace',rarity:'Common',name:{fa:'necklace 35',en:'Necklace 35'},hp:75,def:21,atk:9},
  {id:'necklace_36',type:'necklace',rarity:'Rare',name:{fa:'necklace 36',en:'Necklace 36'},hp:85,def:24,atk:5},
  {id:'necklace_37',type:'necklace',rarity:'Epic',name:{fa:'necklace 37',en:'Necklace 37'},hp:85,def:24,atk:6},
  {id:'necklace_38',type:'necklace',rarity:'Legendary',name:{fa:'necklace 38',en:'Necklace 38'},hp:85,def:24,atk:7},
  {id:'necklace_39',type:'necklace',rarity:'Rare',name:{fa:'necklace 39',en:'Necklace 39'},hp:85,def:24,atk:8},
  {id:'necklace_40',type:'necklace',rarity:'Epic',name:{fa:'necklace 40',en:'Necklace 40'},hp:85,def:24,atk:9},
  {id:'necklace_41',type:'necklace',rarity:'Common',name:{fa:'necklace 41',en:'Necklace 41'},hp:95,def:27,atk:5},
  {id:'necklace_42',type:'necklace',rarity:'Rare',name:{fa:'necklace 42',en:'Necklace 42'},hp:95,def:27,atk:6},
  {id:'necklace_43',type:'necklace',rarity:'Epic',name:{fa:'necklace 43',en:'Necklace 43'},hp:95,def:27,atk:7},
  {id:'necklace_44',type:'necklace',rarity:'Legendary',name:{fa:'necklace 44',en:'Necklace 44'},hp:95,def:27,atk:8},
  {id:'necklace_45',type:'necklace',rarity:'Common',name:{fa:'necklace 45',en:'Necklace 45'},hp:95,def:27,atk:9},
  {id:'necklace_46',type:'necklace',rarity:'Rare',name:{fa:'necklace 46',en:'Necklace 46'},hp:105,def:30,atk:5},
  {id:'necklace_47',type:'necklace',rarity:'Epic',name:{fa:'necklace 47',en:'Necklace 47'},hp:105,def:30,atk:6},
  {id:'necklace_48',type:'necklace',rarity:'Legendary',name:{fa:'necklace 48',en:'Necklace 48'},hp:105,def:30,atk:7},
  {id:'necklace_49',type:'necklace',rarity:'Rare',name:{fa:'necklace 49',en:'Necklace 49'},hp:105,def:30,atk:8},
  {id:'necklace_50',type:'necklace',rarity:'Epic',name:{fa:'necklace 50',en:'Necklace 50'},hp:105,def:30,atk:9},
  {id:'belt_leather_01',type:'belt',rarity:'Common',name:{fa:'belt Leather 01',en:'Belt Leather 01'},def:3,hp:12,spd:1,hero:'rostam'},
  {id:'belt_steel_01',type:'belt',rarity:'Rare',name:{fa:'belt Steel 01',en:'Belt Steel 01'},def:3,hp:12,spd:2,hero:'arash'},
  {id:'belt_golden_01',type:'belt',rarity:'Epic',name:{fa:'belt Golden 01',en:'Belt Golden 01'},def:3,hp:12,spd:3,hero:'fereydun'},
  {id:'belt_royal_01',type:'belt',rarity:'Legendary',name:{fa:'belt Royal 01',en:'Belt Royal 01'},def:3,hp:12,spd:4,hero:'garshasp'},
  {id:'belt_legend_01',type:'belt',rarity:'Common',name:{fa:'belt Legend 01',en:'Belt Legend 01'},def:3,hp:12,spd:5,hero:'rostam'},
  {id:'belt_dark_01',type:'belt',rarity:'Rare',name:{fa:'belt Dark 01',en:'Belt Dark 01'},def:7,hp:24,spd:1,hero:'arash'},
  {id:'belt_ancient_01',type:'belt',rarity:'Epic',name:{fa:'belt Ancient 01',en:'Belt Ancient 01'},def:7,hp:24,spd:2,hero:'fereydun'},
  {id:'belt_magic_01',type:'belt',rarity:'Legendary',name:{fa:'belt Magic 01',en:'Belt Magic 01'},def:7,hp:24,spd:3,hero:'garshasp'},
  {id:'belt_war_01',type:'belt',rarity:'Rare',name:{fa:'belt War 01',en:'Belt War 01'},def:7,hp:24,spd:4,hero:'rostam'},
  {id:'belt_shadow_01',type:'belt',rarity:'Epic',name:{fa:'belt Shadow 01',en:'Belt Shadow 01'},def:7,hp:24,spd:5,hero:'arash'},
  {id:'belt_11',type:'belt',rarity:'Common',name:{fa:'belt 11',en:'Belt 11'},def:11,hp:36,spd:1},
  {id:'belt_12',type:'belt',rarity:'Rare',name:{fa:'belt 12',en:'Belt 12'},def:11,hp:36,spd:2},
  {id:'belt_13',type:'belt',rarity:'Epic',name:{fa:'belt 13',en:'Belt 13'},def:11,hp:36,spd:3},
  {id:'belt_14',type:'belt',rarity:'Legendary',name:{fa:'belt 14',en:'Belt 14'},def:11,hp:36,spd:4},
  {id:'belt_15',type:'belt',rarity:'Common',name:{fa:'belt 15',en:'Belt 15'},def:11,hp:36,spd:5},
  {id:'belt_16',type:'belt',rarity:'Rare',name:{fa:'belt 16',en:'Belt 16'},def:15,hp:48,spd:1},
  {id:'belt_17',type:'belt',rarity:'Epic',name:{fa:'belt 17',en:'Belt 17'},def:15,hp:48,spd:2},
  {id:'belt_18',type:'belt',rarity:'Legendary',name:{fa:'belt 18',en:'Belt 18'},def:15,hp:48,spd:3},
  {id:'belt_19',type:'belt',rarity:'Rare',name:{fa:'belt 19',en:'Belt 19'},def:15,hp:48,spd:4},
  {id:'belt_20',type:'belt',rarity:'Epic',name:{fa:'belt 20',en:'Belt 20'},def:15,hp:48,spd:5},
  {id:'belt_21',type:'belt',rarity:'Common',name:{fa:'belt 21',en:'Belt 21'},def:19,hp:60,spd:1},
  {id:'belt_22',type:'belt',rarity:'Rare',name:{fa:'belt 22',en:'Belt 22'},def:19,hp:60,spd:2},
  {id:'belt_23',type:'belt',rarity:'Epic',name:{fa:'belt 23',en:'Belt 23'},def:19,hp:60,spd:3},
  {id:'belt_24',type:'belt',rarity:'Legendary',name:{fa:'belt 24',en:'Belt 24'},def:19,hp:60,spd:4},
  {id:'belt_25',type:'belt',rarity:'Common',name:{fa:'belt 25',en:'Belt 25'},def:19,hp:60,spd:5},
  {id:'belt_26',type:'belt',rarity:'Rare',name:{fa:'belt 26',en:'Belt 26'},def:23,hp:72,spd:1},
  {id:'belt_27',type:'belt',rarity:'Epic',name:{fa:'belt 27',en:'Belt 27'},def:23,hp:72,spd:2},
  {id:'belt_28',type:'belt',rarity:'Legendary',name:{fa:'belt 28',en:'Belt 28'},def:23,hp:72,spd:3},
  {id:'belt_29',type:'belt',rarity:'Rare',name:{fa:'belt 29',en:'Belt 29'},def:23,hp:72,spd:4},
  {id:'belt_30',type:'belt',rarity:'Epic',name:{fa:'belt 30',en:'Belt 30'},def:23,hp:72,spd:5},
  {id:'belt_31',type:'belt',rarity:'Common',name:{fa:'belt 31',en:'Belt 31'},def:27,hp:84,spd:1},
  {id:'belt_32',type:'belt',rarity:'Rare',name:{fa:'belt 32',en:'Belt 32'},def:27,hp:84,spd:2},
  {id:'belt_33',type:'belt',rarity:'Epic',name:{fa:'belt 33',en:'Belt 33'},def:27,hp:84,spd:3},
  {id:'belt_34',type:'belt',rarity:'Legendary',name:{fa:'belt 34',en:'Belt 34'},def:27,hp:84,spd:4},
  {id:'belt_35',type:'belt',rarity:'Common',name:{fa:'belt 35',en:'Belt 35'},def:27,hp:84,spd:5},
  {id:'belt_36',type:'belt',rarity:'Rare',name:{fa:'belt 36',en:'Belt 36'},def:31,hp:96,spd:1},
  {id:'belt_37',type:'belt',rarity:'Epic',name:{fa:'belt 37',en:'Belt 37'},def:31,hp:96,spd:2},
  {id:'belt_38',type:'belt',rarity:'Legendary',name:{fa:'belt 38',en:'Belt 38'},def:31,hp:96,spd:3},
  {id:'belt_39',type:'belt',rarity:'Rare',name:{fa:'belt 39',en:'Belt 39'},def:31,hp:96,spd:4},
  {id:'belt_40',type:'belt',rarity:'Epic',name:{fa:'belt 40',en:'Belt 40'},def:31,hp:96,spd:5},
  {id:'belt_41',type:'belt',rarity:'Common',name:{fa:'belt 41',en:'Belt 41'},def:35,hp:108,spd:1},
  {id:'belt_42',type:'belt',rarity:'Rare',name:{fa:'belt 42',en:'Belt 42'},def:35,hp:108,spd:2},
  {id:'belt_43',type:'belt',rarity:'Epic',name:{fa:'belt 43',en:'Belt 43'},def:35,hp:108,spd:3},
  {id:'belt_44',type:'belt',rarity:'Legendary',name:{fa:'belt 44',en:'Belt 44'},def:35,hp:108,spd:4},
  {id:'belt_45',type:'belt',rarity:'Common',name:{fa:'belt 45',en:'Belt 45'},def:35,hp:108,spd:5},
  {id:'belt_46',type:'belt',rarity:'Rare',name:{fa:'belt 46',en:'Belt 46'},def:39,hp:120,spd:1},
  {id:'belt_47',type:'belt',rarity:'Epic',name:{fa:'belt 47',en:'Belt 47'},def:39,hp:120,spd:2},
  {id:'belt_48',type:'belt',rarity:'Legendary',name:{fa:'belt 48',en:'Belt 48'},def:39,hp:120,spd:3},
  {id:'belt_49',type:'belt',rarity:'Rare',name:{fa:'belt 49',en:'Belt 49'},def:39,hp:120,spd:4},
  {id:'belt_50',type:'belt',rarity:'Epic',name:{fa:'belt 50',en:'Belt 50'},def:39,hp:120,spd:5},
];
